// ==UserScript==
// @name       Aurora Gender Highlighter
// @namespace  lukasPoehn
// @version    0.1.0
// @description  Script to find ungendered Words in your Aurora work
// @match      https://aurora.iguw.tuwien.ac.at/course/dwi/challenge/*
// @copyright  2018+, Lukas Pöhn
// @require    http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
// ==/UserScript==

/*
 Changelog:
 v0.1.0 (2018)
 Initial prototype
 */

(function AuroraGenderHighlighterClass() {
    var self = this;

    self.init = function () {
        self.extendJQuery();
        self.detectUngenderendWords();
    };

    self.extendJQuery = function () {
        jQuery.fn.justtext = function () {
            return $(this).clone()
                .children()
                .remove()
                .end()
                .text().trim();
        };
    };

    self.detectUngenderendWords = function () {
        var genderMap = {
        'Absender': 'abgesandt durch',
        'Absolventen': 'Abschluss inhabende Person; Person mit Abschluss',
        'Absolventenpraktikum': 'Praktikum (direkt) nach Studienabschluss',
        'Abteilungsleiter': 'Abteilungsleitung',
        'Abteilungsleitertreffen': 'Treffen der Abteilungsleitungen',
        'Administrator': 'Administration; Admin',
        'Adressat': 'Zielperson',
        'Agent': 'auskundschaftende Person; spionierende Person',
        'Akademiker': 'Studierte',
        'Akteure': 'Beteiligte; Agierende; Handelnde',
        'Aktionär': 'Person mit Aktienbesitz',
        'Aktionäre': 'Aktien-/Anteilshabende',
        'Aktionärsversammlung': 'Versammlung von Personen mit Aktienbesitz',
        'Alkoholiker': 'alkoholsüchtige Person; Person mit Alkoholsucht',
        'Alkoholiker': 'Alkoholsüchtige; Menschen mit Alkoholsucht',
        'Altenpfleger': 'Pflegefachkraft',
        'Ampelmännchen': 'Ampelfiguren; Ampelfigürchen; Ampelmenschlein',
        'Anbieter': 'Angebot (von...); Herstellung; angebotsstellende Person; angebotsmachende Person',
        'andere': 'Gegenüber',
        'Anfänger': 'Unerfahrene; Menschen ohne Vorkenntnisse; Menschen ohne Vorerfahrung; Beginnende',
        'Das Angebot richtet sich an Anfänger und Fortgeschrittene.': '... Das Angebot richtet sich an Personen mit und ohne Vorkenntnisse.',
        'Anfängerkurs': 'Einstiegskurs; Grundkurs; Kurs für Menschen ohne Vorkenntnisse; Kurs für Menschen ohne Vorerfahrung',
        'Angehöriger': 'Familienmitglied',
        'Angeklagter': 'angeklagte Person',
        'Anhänger': 'Fans; Begeisterte',
        'Anhänger': 'Gleichgesinnte; Unterstützende; Sympathisierende; sich [einer Bewegung] Zuordnende',
        'Animateur': 'Freizeitbetreuungsperson',
        'Sprachanimateur': 'noch kein passender Begriff gefunden;',
        'Animateure': 'Animierende',
        'Anleger': 'Anlegende',
        'Anleiter': 'anleitende Person',
        'Ansprechpartner': 'Ansprechperson; Kontakt',
        'Antragsteller': 'beantragende Person/Einrichtung; die Person, die einen Antrag stellt; die antragstellende Person; Antrag gestellt von ...',
        'Antragsteller werden in Kürze benachrichtigt.': '... Sie werden kurz nach Antragstellung benachrichtigt.',
        'Anwalt': 'Rechtsbeistand',
        'Anwaltskosten': 'Kosten für die Rechtsvertretung',
        'Anwender': 'Nutzende; Anwendende; Personen, die ... anwenden; Anwendung',
        'anwenderbezogen': 'anwendungsbezogen; praxisbezogen',
        'Anwohner': 'alle, die in dieser Straße wohnen; Anwohnende; Nachbarschaft',
        'Apotheker': 'Arzneikundige',
        'Fragen Sie Ihren Arzt oder Apotheker.': '... Holen Sie sich ärztlichen oder pharmazeutischen Rat. / Holen Sie sich bei Fragen ärztlichen Rat oder erkundigen Sie sich in Ihrer Apotheke.',
        'Arbeiter': 'Arbeitskraft',
        'Arbeiter': 'Erwerbstätige; Belegschaft; Beschäftigte',
        'Arbeitgeber': 'Führungskraft',
        'Arbeitgeber': 'Arbeitgebende; Betriebe; Unternehmen',
        'Das ist ein Aspekt, der für seine späteren Arbeitgeber interessant ist.': '... Das ist ein Aspekt, der für ihn im späteren Bewerbungsprozess von Vorteil ist.',
        'Arbeitnehmer': 'Beschäftigte; Arbeitskräfte; Belegschaft; Personal',
        'Architekten': 'Architekturschaffende',
        'Arzt': 'Person im ärztlichen Dienst; ärztliches Fachpersonal',
        'Ärzte': 'ärztliches (Fach-)Personal',
        'Arztbesuch': 'ärztlicher Kontakt; ärztliche Sprechstunde; Besuch der ärztlichen Sprechstunde; ärztliche Visite',
        'Arztbrief': 'Entlassungsbrief; Entlassbericht; ärztlicher/medizinischer (Abschluss-)Bericht; ärztliche Epikrise; ärztlicher Brief; (ärztlicher) Befundbericht; ärztliches Informationsschreiben; ärztliche Information',
        'Arztgeheimnis': 'ärztliche Schweigepflicht',
        'Arzthelferinnen': 'Medizinische Fachangestellte',
        'Arztkoffer /-köfferchen': 'Behandlungstasche; Medizinkoffer /-köfferchen',
        'Arztkosten': '(ärztliche) Behandlungskosten',
        'Arzt-Patienten-Verhältnis': 'noch kein passender Begriff gefunden;',
        'Arztpraxis': 'Praxis für ...-medizin (z.B. Praxis für Allgemeinmedizin); ärztliche Praxis',
        'Arzttermin': 'Behandlungstermin; Vorsorgetermin',
        'Arztwahl': 'Wahl des ärztlichen Fachpersonals',
        'Assistent': 'Assistenz',
        'Assistenzarzt': 'Person in fachärztlicher Weiterbildung; ärztliches Fachpersonal in Weiterbildung',
        'Asylbewerber': 'Asylsuchende; Personen im Asylverfahren',
        'Athlet': 'sporttreibende Person',
        'Athleten': 'Sporttreibende; Wettkämpfende',
        'Attentäter': 'Person, die ein Attentat verübt',
        'Auftraggeber': 'Auftraggebende; auftraggebende Personen; in Auftrag gegeben von... ; beauftragt von...',
        'Auftragnehmer': 'einen Auftrag entgegen nehmende / annehmende Person',
        'Augenoptiker (Geschäft mit Werkstatt)': 'Optikfachgeschäft',
        'Ausländer': 'Person aus dem Ausland; Person nichtdeutscher Herkunft; ausländische Person; Person mit anderer Staatsangehörigkeit',
        'Ausländerbehörde': 'Migrationsamt/-stelle; Zuwanderungsamt/-stelle',
        'Aussiedler': 'ausgesiedelte Person',
        'Aussiedler': 'ausgesiedelte Personen',
        'Aussteller': 'noch kein passender Begriff gefunden;',
        'Ausstellerausweis': 'noch kein passender Begriff gefunden',
        'Ausstellerliste': 'noch kein passender Begriff gefunden',
        'Auszubildender': 'Nachwuchskraft; Person in Ausbildung; auszubildende Person; lernende Person',
        'Auszubildende': '[im Plural ist dieses Wort schon gendergerecht]',
        'Autor': 'bücherschreibende Person',
        'Autoren': 'Autorenschaft; Urheberrechtsinhabende; Verfassende; Schreibende; Literaturschaffende',
        'Bankräuber': 'Bankausraubende',
        'Bauarbeiter': 'Bauarbeiten ausführendes (Fach-)Personal',
        'Bauern': 'Landwirtschaft Betreibende; landwirtschaftlich Beschäftigte; Beschäftigte in der Landwirtschaft',
        'Bauherr': 'den Bau in Auftrag gebende Person',
        'Bauherren': 'Bauende',
        'Beamter': 'verbeamtete Person; Person im Beamtenstatus; der/die Beamte (Kurzform von der/die Beamtete)',
        'Beamtenlaufbahn': 'verbeamteter Werdegang; Laufbahn im öffentlichen Dienst mit Aussicht auf Verbeamtung',
        'Bearbeiter': 'den Vorgang betreuende Person; zuständige Person',
        'Beauftragter': 'beauftragte Person',
        'Bediener': 'bedienende Person',
        'Befragter': 'befragte Person; Person, die befragt wurde',
        'Befürworter': 'Unterstützung; Zustimmende',
        'Behinderter': 'Mensch mit Behinderung',
        'Beisitzer': 'Beisitzende',
        'Bekannter': 'Person aus dem Bekanntenkreis; (mir) bekannte Person; Bekanntschaft',
        'bemannt': 'besetzt; mit Personen besetzt; astronautisch',
        'bemuttern': 'fürsorglich sein, verhätscheln, umsorgen',
        'Benutzer': 'Anwendende; Nutzende',
        'benutzerfreundlich': 'praktisch / leicht zu bedienen; bedienungsfreundlich; benutzungsfreundlich',
        'Benutzername': 'Nickname; Pseudonym',
        'Benutzeroberfläche': 'Bedienoberfläche; Benutzungsoberfläche',
        'Benutzerordnung': '(Be-)Nutzungsordnung',
        'Beobachter': 'Beobachtende',
        'Berater': 'beratende Person; die Beratung erfolgt durch... ; Sie werden beraten von ...',
        'Beratertätigkeit': 'beratende Tätigkeit, Beratung',
        'bergmännisch': 'Berichterstatter Bericht erstattende Person',
        'Berichterstatter': 'Berichtende',
        'Berliner': 'die Berliner Bevölkerung',
        'Berufsanfänger': 'Berufsunerfahrene',
        'Beschäftigter': 'Arbeitskraft',
        'Beschuldigter': 'beschuldigte Person',
        'Besitzer': 'besitzhabende Person',
        'Besitzer von Immobilieneigentum': 'Immobilien besitzende Person',
        'Besucher': 'Gäste* (*siehe Anmerkung unter Gäste); Publikum; Besuche',
        'Besuchergruppe': 'Besuchsgruppe',
        'Betrachter': 'Betrachtende',
        'Betreiber': 'Betriebsgesellschaft; betreibende Firma',
        'Betreuer': 'Betreuungsperson',
        'Betriebsrat': 'Mitglied des Betriebsrates',
        'Betriebsräte': 'Mitglieder des Betriebsrates; der Betriebsrat; Mitarbeitendenvertretung; der Personalrat',
        'Betroffener': 'betroffene Person; Opfer',
        'Bewerber': 'sich bewerbende Person',
        'Bewerber': 'Bewerbende; sich bewerbende Personen',
        'Bewerberzahlen': 'Bewerbungszahlen',
        'Bewohner': 'in ... Lebende; in ... lebende Menschen',
        'Blockwart': 'noch kein passender Begriff gefunden',
        'Blogger': 'bloggende Personen; Personen, die einen Blog schreiben',
        'Briefträger': 'Briefzustellung; Postzustellung',
        'Brüderlichkeit': 'Mitmenschlichkeit; Solidarität',
        'Buhmann': 'Sündenbock; Feindbild',
        'Bundespräsidentenwahl': 'Bundespräsidentschaftswahl; BP-Wahl',
        'Bürger': 'Mitglied des Staates / der Stadt;',
        'Bürger': 'Bevölkerung; Einwohnerschaft; (Kommunal-)Wahlberechtigte; Staatsangehörige; Einheimische; im Ort/in der Stadt ... Wohnende',
        'Bürgermeister': 'Stadtoberhaupt',
        'Bürgerrechte': 'Rechte des deutschen (oder anderer Staaten) Staatsvolkes',
        'Bürgersteig': 'Gehweg; Fußweg',
        'Bürgerzentrum': 'Kulturzentrum; Stadtteilzentrum; selbstverwaltetes Zentrum',
        'Busfahrer': 'Busführung; busführende Person',
        'Chef': 'vorgesetzte Person; Leitungsperson; Leitung',
        'Chefs': 'Vorgesetzte; Leitung',
        'Chefsache': 'Sache mit oberster Priorität; Angelegenheit mit besonderer Wichtigkeit; dringliche Sache',
        'Chemiker': 'Fachkraft für Chemie',
        'Chirurgenstahl': 'Chirurgiestahl',
        'Christen': 'Menschen christlichen Glaubens',
        'Coach': 'Begleitung; Beratung',
        'Damenprogramm': 'Begleitprogramm',
        'Dekan': 'Leitung des Dekanats; Dekanat',
        'Demonstranten': 'Demonstrierende',
        'Designer': 'Designschaffende',
        'Deutscher': 'Person aus Deutschland; deutsche Person; Person mit deutscher Staatsangehörigkeit',
        'Dienstherrengenehmigung': 'Vorgesetztengenehmigung',
        'Dienstleister': 'dienstleistende Person; dienstleistendes Unternehmen',
        'Diplomingenieur': 'diplomierte technische Fachkraft',
        'Geschlecht, 2013': '... Anteil von Forschenden und diplomierten technischen Fachkräften an der Gesamtarbeitskraft nach Geschlecht, 2013',
        'Dirigent': 'unter dem Dirigat von ...; unter Leitung von DJ der/die DJ',
        'Doktoranden': 'Promovierende',
        'Doktorandenkolleg': 'Promotionskolleg; Promovierendenkolleg',
        'Dolmetscher': '(simultan-)übersetzende Fachkraft',
        'Dönermann': 'Dönerbude; Kebapverkauf.',
        'Dozent': 'lehrende Person; Lehrkraft; Lehrperson; vortragende Person',
        'Dozenten': 'Dozierende; Lehrpersonal; Lehrende',
        'Dozententätigkeit': 'Lehrtätigkeit',
        'Ehegatten': 'Eheleute',
        'Ehepartner': 'geehelichte Person',
        'Ehrenamtler': 'Ehrenamtliche; Freiwillige; (ehrenamtlich) Engagierte',
        'Ehrenmann': 'Ehrenperson',
        'Eigentümer': '(im) Eigentum von ...',
        'Ein-Mann-Betrieb': 'Ein-Personen-Betrieb',
        'Einsteigerkurs': 'Einstiegskurs; Grundlagenkurs; Grundkurs; Basiskurs',
        'Einwanderer': 'Menschen mit Migrationshintergrund /-geschichte /-biografie',
        'Einwohner': 'die Menschen der Stadt XY; Population; Bevölkerung',
        'Einzelne': '[im Plural ist dieses Wort schon gendergerecht]',
        'Empfänger': 'empfangen von... ; für... ; bestimmt für...',
        'Enkel': 'Enkelkind',
        'Entdecker': 'entdeckt von ...',
        'Entdecker': 'entdeckt von ... ; entdeckende Personen /Kinder; Forschende; Entdeckende',
        'Entscheidungsträger': 'Person mit Entscheidungsbefugnis',
        'Entwickler': 'Entwickelnde; Erfindende',
        'Erben': 'Erbberechtigte',
        'Ermittler': 'Ermittelnde; Ermittlungsteam',
        'Erstsemester': 'Studierende im ersten Semester',
        'Erzieher': 'pädagogische Fachkraft; Erziehungskraft',
        'Experte': 'Fachgröße; Autorität; Koryphäe; Person vom Fach',
        'Experten': 'Fachkräfte; Fachleute; Fachkundige; Sachverständige',
        'Expertengruppe': 'Fachgruppe',
        'Expertentagung': 'Fachtagung',
        'Expertenwissen': 'Fachwissen; Expertise',
        'Facharzt': 'ärztliche Fachkraft',
        'Fachmann': 'Fachkraft',
        'fachmännisch': 'fachkundig',
        'Fachwissenschaftler': 'Fachforschende',
        'Fahrer': 'Fahrdienst',
        'Fahrer': 'Fahrzeugführende; Fahrende',
        'Fahrgast': 'mitreisende Person; gegen Entgelt transportierte Person',
        'Fahrgäste': 'Mitfahrende; Reisende',
        'Fahrradfahrer': 'Fahrrad Fahrende; wer mit dem Fahrrad unterwegs ist...',
        'Fahrzeughalter': 'eine ein Fahrzeug besitzende Person',
        'Familienhelfer': 'Familienhilfe; Familien unterstützende (Fach-)Kraft; die die Familie X. unterstützende Fachperson/Fachkraft; im familienunterstützenden Dienst arbeitende / angestellte Person',
        'Fan': 'in besonderem Maße begeisterte Person',
        'Fans': 'Begeisterte',
        'Favorit': 'favorisierte (antretende) Person; favorisierte Option',
        'Feind': 'noch kein passender Begriff gefunden;',
        'Feuerwehrmänner': 'Einsatzkräfte der Feuerwehr; Feuerwehrangehörige; Feuerwehr; Feuerwehrleute',
        'Filmemacher': 'filmschaffende Person',
        'Filmemacher': 'Filmschaffende',
        'Filmstar': 'Filmgröße; Filmberühmtheit',
        'Finanzintermediäre': 'Anbietende von Finanzintermediation; Finanzintermediierende',
        'Flüchtlinge': 'Geflüchtete; Flüchtende; geflüchtete Menschen',
        'Förderer': 'Stelle, die Fördermittel vergibt',
        'Förderer': 'unterstützender Personenkreis',
        'Fördermittelgeber': 'Stelle, die Fördermittel vergibt; fördermittelgebende Stelle',
        'Forscher': 'Forschende; Universitätsmitglieder; wissenschaftliches Personal der Universität; Menschen, die in der Forschung tätig sind; Forschungsteam',
        'Forschergemeinde': 'Forschungsgemeinde',
        'Forscherkolloquium': 'Forschungskolloquium',
        'Forscherteam': 'Forschungsteam',
        'Fortgeschrittene': '[im Plural ist dieses Wort schon gendergerecht]',
        'Fotograf': 'noch kein passender Begriff gefunden',
        'Fotografen': 'Fotografierende; Aufnehmende',
        'Freund': '(enge) Bezugsperson; Herzensmensch; Bekanntschaft',
        'Freunde': 'Bekannte; Bezugspersonen',
        'Führerschein': 'Fahrerlaubnis; Fahrberechtigung',
        'Funktionär': 'in Funktion gewählte Person; verantwortliche/beauftragte/bevollmächtigte Person',
        'Funktionsträger': 'in Funktion gewählte Person; verantwortliche/beauftragte/bevollmächtigte Person',
        'Fußballspieler': 'Fußballspielende',
        'Fußgänger': 'Menschen zu Fuß; zu Fuß Gehende',
        'Fußgängerstreifen': 'Zebrastreifen',
        'Fußgängerweg': 'Gehweg',
        'Fußgängerzone': 'Flanierzone; Einkaufsstraße; verkehrsfreie Zone; verkehrsberuhigter Bereich',
        'Gärtner': 'Gartenarbeitskraft',
        'Gast': 'Besuch; Besuchsperson',
        'Gastbeitrag': 'Sonderbeitrag',
        'Gäste': 'Eingeladene, Geladene, Besuchefinden.]',
        'Gastgeber': 'Einladende',
        'Gasthörer': 'Studierende im Gaststudium',
        'Gasthörerstatus': 'Gaststudierendenstatus',
        'Gasthörerstudium': 'Gaststudium; Hospitation',
        'Geisterfahrer': 'Fahrzeug in falscher Richtung',
        'Geldgeber': 'Geldgebende; support',
        'Generaldirektor': 'Direktoriumsleitung',
        'Generalist': 'Universalgenie; Multitalent; weitere Alternativen gesucht für Generalist als Gegensatz zu Spezialist;',
        'Geograph': 'noch kein passender Begriff gefunden',
        'Geologe': 'noch kein passender Begriff gefunden',
        'Gerätewart': 'Geräteaufsicht',
        'Geschäftsführer': 'Geschäftsführung; Geschäftsleitung',
        'Geschäftsmänner': 'Geschäftsleute',
        'Geschäftspartner': 'geschäftliche Verbindung',
        'Gesellschafter': 'Betriebsgesellschaft',
        'Gesetzgeber': 'Legislative; gesetzgebende Instanz; Gesetzgebende',
        'Gesprächspartner': 'Gesprächsbeteiligte; Gegenüber',
        'Gewinner': 'Erster Platz',
        'Gläubiger': 'Geld-/Kreditgebende',
        'Götter': 'Allwissende; Allmächtige; übernatürliche Wesen; Ewige; Gottheiten',
        'Grinsepeter': 'Grinsebacke; Grinsegesicht; Grinsekuchen',
        'Gründer': 'gründende Person',
        'Gründerzeit': 'Gründungszeit',
        'Gruppenleiter': 'Gruppenleitende; Gruppenleitung',
        'Gutachter': 'begutachtet von ...',
        'Gutachter': 'Sachverständige',
        'Hacker': 'Personen, die fremde Digitaldaten nutzen; Hackende; ',
        'Hackerangriff': 'Hackingangriff; Hackangriff',
        'Hamburger': 'die Hamburger Bevölkerung',
        'Handwerker': 'noch kein passender Begriff gefunden;',
        'Handwerker': 'Handwerksbetriebe',
        'Hausherr': 'Familienvorstand; Hausvorstand',
        'Hausmeister': 'Gebäudemanagement',
        'Hebammen': 'Geburtshelfende',
        'Held': 'Schlüsselperson; Hauptperson; außerordentlich erfolgreiche Person',
        'Helfer': 'Hilfskraft; Assistenz',
        'Helfer': 'Helfende',
        'Herausgeber': 'herausgegeben von ...',
        'Herrscher': 'Staatsoberhaupt',
        'Hersteller': 'Herstellfirma',
        'Hexe': '(schwarze) Zauberkraft innehabende Person; Person mit (schwarzen) Zauberkräften; mit Zauberkräften ausgestattete Person',
        'Ich-Erzähler': 'Ich-Form; Ich-Figur; erzählendes Ich',
        'Immigranten': 'Menschen mit Migrationshintergrund /-geschichte /-biografie',
        'Immobilienbesitzer': 'Immobilienbesitzende',
        'Individuum': '[als Neutrum ist dieses Wort schon gendergerecht  DAS Individuum]',
        'Informant': 'Informationsquelle; Quelle',
        'Informatiker': 'auf den IT-Bereich spezialisierte Person',
        'Ingenieurberuf': 'Ingenieursberuf',
        'Ingenieure': 'noch kein passender Begriff gefunden;',
        'Ingenieurwesen': 'Technikwissenschaften; technische Wissenschaften; Technik',
        'Inhaber': 'etwas innehabende Person',
        'Initiatoren': 'Initiierende',
        'Investoren': 'Investierende',
        'Interessenten': 'Interessierte',
        'Interviewer': 'interviewende Person',
        'Interviewer': 'Interviewende',
        'Interviewpartner': 'Interviewte',
        'Jäger': 'jagende Person; Person auf der Jagd',
        'Jäger': 'Jägerschaft; jagende Personen; Personen auf der Jagd',
        'jeder': 'alle; alle für sich',
        'jedermann': 'alle',
        'jemand, der ...': 'eine Person, die ...; ein Mensch, der ...',
        'Journalist': 'Presse; Medien; jemand von der Presse/vom Fernsehen/...; wer für die Zeitung/fürs Fernsehen berichtet',
        'Journalisten': 'im Journalismus Tätige/Arbeitende; Medienschaffende; Presse; die Medien',
        'Juden': 'Menschen jüdischen Glaubens; jüdische Menschen; Mitglieder / Angehörige der jüdischen Gemeinschaft / des jüdischen Volkes',
        'Jugendlicher': 'junge Person; junger Mensch; Teenie; Teen; Teenager',
        'Kameramänner': 'Kamerateam',
        'Kandidaten': 'Kandidierende',
        'Kandidatenfragen': 'Personalfrage; K-Frage',
        'Kandidatenvorschlag': 'Personalvorschlag',
        'Kanzler': 'Regierung (an-)führende Person; Regierungsoberhaupt',
        'Kanzleramt': 'noch kein passender Begriff gefunden;',
        'Kassierer': 'Person an der Kasse',
        'Katholiken': 'Menschen katholischen Glaubens',
        'kaufmännisch': 'zahlentechnisch; finanztechnisch; in Zahlen gesehen',
        'keiner': 'niemand',
        'Kellner': 'Servicekraft; Bedienung',
        'Kinderarztpraxis': 'Praxis für Kinderheilkunde',
        'Kindermädchen': 'Kinderbetreuung; Aupair',
        'Kläger': 'klagende Person',
        'Kleinbauern': 'kleine Landwirtschaftsbetriebe',
        'Klient': 'ratsuchende Person; Beratung in Anspruch nehmende Person; Person, die in die Beratung kommt; Fall; Besuch',
        'Klienten': 'Klientel',
        'klientenorientiert': 'orientiert am Bedarf der ratsuchenden Person',
        'Kollegen': 'Kollegschaft; Kollegium',
        'Kommentator': 'kommentierender Pressemensch; kommentierende Presse',
        'Kommentatoren': 'Kommentar von Medienschaffenden',
        'Kommilitonen': 'Mitstudierende',
        'Komponist': 'musikschaffende Person; kompositionstätige Person',
        'Komponisten': 'Musikschaffende; Kompositionstätige',
        'Konfirmand': 'noch kein passender Begriff gefunden;',
        'Konfirmanden': 'Jugendliche in der Konfirmationsvorbereitung',
        'Konfirmandenunterricht': 'Konfirmationsunterricht',
        'Kontrahent': 'Gegenüber',
        'Kontoinhaber': 'kontoinhabende Person',
        'Konkurrent': 'Konkurrenz',
        'Konsumenten': 'Konsumierende; Kundschaft; einkaufende / konsumierende Zielgruppe',
        'Kooperationspartner': 'in Kooperation mit',
        'Koordinator': 'Koordination',
        'Krankenschwester': 'Pflegefachkraft',
        'Krankenschwestern': 'Pflegepersonal; Beschäftigte in der Krankenpflege',
        'Kreditnehmer': 'kreditnehmende Person',
        'Kreditnehmer': 'Kreditnehmende',
        'Kritiker': 'Kritisierende; Kritische; kritische Stimmen',
        'Küchenhelfer': 'Küchenhilfe',
        'Kunde': 'Kundschaft',
        'Kundenauftrag': 'Auftrag durch Kundschaft; Auftrag',
        'Kundenbedürfnisse': 'Bedürfnisse der Kundschaft',
        'Kundenberatung': 'Beratung der Kundschaft',
        'kundenfreundlich': 'praktisch zu bedienen; publikumsfreundlich; nutzungsfreundlich',
        'kundenorientiert': 'publikumsorientiert',
        'Kundenwerbung': 'Akquise',
        'Kundenwünsche': 'Wünsche der Kundschaft',
        'Kunstfreunde': 'Kunstbegeisterte',
        'Künstler': 'Kunstschaffende',
        'Künstlername': '(künstlerisches) Pseudonym; Kunstname',
        'Laborant': 'Laborfachkraft',
        'Laborarbeiter': 'Laborfachkraft',
        'Laie': 'Mensch ohne Fachkenntnisse; fachunkundige Person; fachfremde Person',
        'Laien': 'Fachunkundige; Fachfremde',
        'Landsmänner': 'Landsleute',
        'Landwirte': 'Landwirtschaft Betreibende; landwirtschaftlich Beschäftigte; Beschäftigte in der Landwirtschaft',
        'Lehrer': 'Lehrperson',
        'Lehrer': 'Lehrkräfte; Lehrpersonen; das Kollegium; Lehrende',
        'Lehrerpult': 'Tisch/Pult der Lehrkraft',
        'Lehrerzimmer': 'Arbeitszimmer der Lehrkräfte; Teamraum',
        'Lehrling': 'Nachwuchskraft; Person in Ausbildung; auszubildende Person; lernende Person',
        'Lehrlinge': 'Auszubildende; Lernende',
        'Lehrstuhlinhaber': 'Leitung des Lehrstuhles',
        'Lehrstuhlinhaber': 'Leitende eines Lehrstuhles',
        'Lehrstuhlleiter': 'Leitung des Lehrstuhls',
        'Lehrstuhlleiter': 'Leitende eines Lehrstuhles',
        'Leistungsbezieher': 'Leistung Beziehende',
        'Leiter': 'Leitung',
        'Lektor': 'noch kein passender Begriff gefunden',
        'Lektorstelle': 'Lektoratsstelle',
        'Leser': 'Leserschaft; lesende Zielgruppe',
        'Leserbrief': 'Kommentar zum Artikel xy',
        'Leserbriefe': 'Ihre Kommentare/Meinungen; offene Zuschriften',
        'leserfreundlich': 'lesefreundlich',
        'Lieber': 'An ...; Hallo ...; Guten Tag Lieferant Lieferfirma',
        'Literaturkritiker': 'Literatur kritisierende Person',
        'Literaturkritiker': 'Literaturkritisierende',
        'Mädchen für alles': 'Mensch für alles',
        'Mädchenname': 'Geburtsname',
        'Magier': 'Zauberkunst ausübende Person',
        'man': 'Sie; viele; wir; ich',
        'Manager': 'Management; Unternehmensführung; Führungskraft',
        'Männchen': 'Figürchen; Spielfigur',
        'Manndeckung': '1 1-Verteidigung; (weitere Alternativen gesucht ',
        'Mannsbild': 'gestandene Person, Powermensch',
        'Mannschaft': 'Team; Gruppe; Kollektiv',
        'Mathematiker': 'mathematisch qualifizierte Person; sich mit Mathematik befassende Person',
        'Matrose': 'Mitglied der Schiffsbesatzung',
        'Medienanbieter': 'Medienorganisationen',
        'Medienpartner': 'in Medienpartnerschaft mit',
        'Mediziner': 'medizinisches/ärztliches Fachpersonal',
        'Meisterschaft': 'Turnier; Wettbewerb',
        'Mentor': 'Vorbild; fürsprechende Person; beratende Person; fördernde Person',
        'Mieter': 'Mietperson; Mietpartei',
        'Mieterverein': 'Mietverein; Mietvertretung',
        'Migrant': 'Person mit Migrationshintergrund; eingewanderte Person; der/die Migrierte',
        'Migranten': 'Personen mit Migrationshintergrund; Eingewanderte; Zugewanderte; Migrierte',
        'Mitarbeiter': 'Mitarbeitende; Beschäftigte; Angestellte; Tätige; Belegschaft; Arbeitskräfte; Kollegium; Personal; Teammitglieder; Werktätige; Betriebs-/Konzern-/Firmen-/Unternehmensangehörige; bei uns beschäftigte',
        'Mitarbeiterführung': 'Personalmanagement; Personführung; Personalpolitik',
        'Mitarbeitergespräch': 'Dienstbesprechung; Qualifikationsgespräch; Arbeitsgespräch; Beurteilungsgespräch; Jahresgespräch; Beschäftigtengespräch; Personalgespräch',
        'Mitarbeiterstellen': 'Stellen für Mitarbeitende; Arbeitsplätze',
        'Mitbewohner': 'Wohnungsteilende',
        'Mitbürger': 'Mitmensch',
        'Mitbürger': 'Landsleute; Mitmenschen; Staatsangehörige',
        'Mitfahrergelegenheit': 'Mitfahrgelegenheit',
        'Mitglied': '[als Neutrum ist dieses Wort schon gendergerecht DAS Mitglied]',
        'Mitglieder': '[als Neutrum ist dieses Wort schon gendergerecht  DAS Mitglied - die Mitglieder ; wer dennoch eine Alternative bevorzugt, kann diese hier nutzen ] Zugehörige; Angehörige; Teil von ...',
        'Mitschüler': 'andere Kinder aus der Klasse / Schule',
        'Mitwisser': 'Eingeweihte',
        'Moderator': 'Moderation',
        'Modeschöpfer': 'Mode Schaffende',
        'Mofafahrer': 'Mofa Fahrende',
        'Mörder': 'einen Mord begehende Person; mordende Person',
        'Multiplikator': 'Person, die Informationen/Wissen weitergibt; Wissen/Informationen weitergebende Person',
        'Münchner': 'die Münchner Bevölkerung',
        'Musiker': 'Musikausübende; Musikschaffende; Musikspielende; Musizierende; Mitglieder eines Orchesters',
        'Muslim': 'Mensch muslimischen Glaubens',
        'Mutter': 'Elternteil',
        'Mutter-Kind-Gruppe': 'Eltern-Kind-Gruppe',
        'Mütterberatung': 'Elternberatung',
        'mütterlicherseits': '(vornamen-)licherseits [bei gleichgeschlechtlichen Elternpaaren]',
        'Muttermilch': 'Elternmilch; Brustmilch [z.B. bei transgeschlechtlichen, stillenden Vätern]',
        'Mutterschutz': 'Elternschutz [auch transgeschlechtliche Väter haben Anspruch auf Mutterschutz]',
        'Muttersprache': 'Heimatsprache; Familiensprache; Erstsprache',
        'Nachbarn': 'nebenan Wohnende',
        'Nachbarn (in einem Wohnhaus; pl.)': 'Hausgemeinschaft',
        'Nachfolger': 'Nachfolge',
        'Nachwuchswissenschaftler': 'wissenschaftlicher Nachwuchs',
        'Namensvetter': 'Gleichnamige',
        'Nutzer': '(be-)nutzende Person; Person, die ... nutzt',
        'Nutzer': 'Personen, die ... nutzen; Nutzung; Mitglieder; Nutzende',
        'Oberarzt': 'ärztliche Führungskraft',
        'Ombudsmann': 'Ombudsperson',
        'Opfer': '[als Neutrum ist dieses Wort schon gendergerecht DAS Opfer; eine gendergerechte Alternative ist nicht erforderlich]',
        'Organisatoren': 'Organisation; Organisationsteam/-komitee; organisiert von ...; Organisierende',
        'Organspender': 'Organ Spendende; Organ spendende Personen',
        'Pächter': 'pachtende Person',
        'Pädagoge': 'pädagogische Fachkraft',
        'Paketbote': 'Paketzustellung',
        'Parlamentarier': 'Abgeordnete',
        'Partner': 'Gegenüber',
        'Partner': 'Unterstützung; Mitglied; Beteiligte; Kooperationen; Partnerorganisationen',
        'Partnerarbeit': 'Zweierarbeit; Paararbeit; Tandemarbeit',
        'Partnerschaft': 'Beziehung; Kooperation; Zusammenarbeit; Tandem',
        'Passagier': 'noch kein passender Begriff gefunden;',
        'Passagiere': 'Reisende',
        'Passanten': 'Vorübergehende',
        'Passantenbefragung': 'Straßenbefragung',
        'Pate': 'Patenamt; Patenschaft',
        'Patienten': 'zu behandelnde Personen; Personen, die in (ärztlicher) Behandlung sind; Kranke; Erkrankte; Menschen mit einer Erkrankung; Menschen, die im Krankenhaus liegen; Betroffene; Behandelte',
        'Patientenkontakt': 'noch kein passender Begriff gefunden;',
        'Patientenschulung (in der Psychologie)': 'noch kein passender Begriff gefunden',
        'patientenorientiert': 'noch kein passender Begriff gefunden',
        'Patientenverfügung': 'Verfügung(en) für betreuende Personen',
        'Patientenversorgung': 'ärztliche Versorgung; Behandlung; Pflege',
        'Patientenzimmer': 'noch kein passender Begriff gefunden;',
        'Pendler': 'Pendelnde',
        'Pendlerpauschale': 'Pendelpauschale; Pauschale für Pendelnde; Pauschale für Menschen, die pendeln',
        'Personalleiter': 'Personalleitung',
        'Personalrat': 'Mitglied des Personalrates',
        'Personalräte': 'Mitglieder des Personalrates; der Personalrat; Mitarbeitendenvertretung',
        'Personalvertreter': 'Personalvertretung',
        'Pfadfinder': 'Scout;',
        'Pfarrer': 'Pfarrperson',
        'Pilot': 'flugzeugführende Belegschaft',
        'Pionier': 'vorkämpfende Person',
        'Planer': 'planende Personen; planende Institutionen',
        'Politiker': 'Menschen in der Politik; Menschen, die in der Politik tätig sind',
        'Polizisten': 'Polizei; Polizeikräfte; Polizeileute',
        'Postbote': 'Postzustellung',
        'Praktikant': 'eine ein Praktikum absolvierende Person; eine Person im Praktikum; eine sich in einem Praktikum(verhältnis) befindende Person',
        'Praktikanten': 'Auszubildende im Praktikum',
        'Praktikantenstelle': 'Praktikumsstelle',
        'Praktiker': 'Praktizierende; Leute aus der Praxis; praktisch veranlagte Menschen',
        'Präsident': 'Staatsoberhaupt; Vorsitz',
        'Präsidenten': 'Vorsitzende',
        'Präsidentenwahl': 'Präsidentschaftswahl',
        'Prediger': 'Predigende',
        'Preisträger': 'ausgezeichnete Person',
        'Proband': 'Testperson; Versuchsperson',
        'Probanden': 'Testpersonen; Versuchspersonen; Teilnehmende',
        'Produzent': 'die Produktionsleitung innehabende Person',
        'Produzenten': 'Produzierende; Produktionsteam',
        'Professor': 'eine Professur innehabende Person',
        'Professoren': 'Professorenschaft',
        'Profi': 'Fachperson; Person mit Fachwissen/Fachkenntnis',
        'Profis': 'Sachkundige; Fachleute; Sachverständige',
        'Projektleiter': 'Projektleitung',
        'Projektträger': 'noch kein passender Begriff gefunden',
        'Proletarier': 'Lohnabhängige; Werktätige; Arbeitende; Angehörige des Proletariats',
        'Protagonist': 'Hauptperson; Hauptfigur; zentrale Gestalt; Schlüsselfigur; Titelrolle',
        'Protokollführer': 'protokollführende Person',
        'Prüfer': 'Prüfungsleitung; Prüfungsabnahme durch...; geprüft von...',
        'Prüfling': 'zu prüfende Person',
        'Psychotherapeut': 'psychotherapeutisches Fachpersonal',
        'Putzfrau': 'Reinigungspersonal; Reinigungskraft; Raumpflege',
        'Rabbiner': 'Mitglied des Rabbinats',
        'Rabbiner': 'Rabbinat',
        'Radfahrer': 'Rad Fahrende; wer mit dem Rad unterwegs ist...',
        'Ratgeber': 'Wegbegleitung; Beistand; ratgebende/beratende Person',
        'Raucherbereich': 'Bereich für Rauchende',
        'Raucherpause': 'Zigarettenpause',
        'Rechnungsprüfer': 'Rechnungsprüfung; Person, die die Rechnungsprüfung macht; Person, die für die Rechnungsprüfung verantwortlich ist',
        'Rechtsanwalt': 'Rechtsbeistand',
        'Redakteur': 'Redaktion; Redationsmitglied',
        'Rednerliste': 'Redeliste',
        'Rednerpult': 'Redepult',
        'Referent': 'referierende Person',
        'Referenten': 'Referierende; Vortragende',
        'Regierungschef': 'Staatsoberhaupt (nur in manchen Fällen möglich); noch kein passender Begriff gefunden;',
        'Reiseleiter': 'Reiseleitung',
        'Rekrut': 'Nachwuchs (der Grundausbildung in der Bundeswehr)',
        'Rektor': 'Schulleitung',
        'Rentner': 'Menschen, im Rentenalter; Menschen, die in der Rente sind',
        'Reporter': 'Presse; berichterstattende Person; Medienvertretung',
        'Repräsentanten': 'Vertretung',
        'Rettungsschwimmer': 'aus dem Wasser rettende Person',
        'Rezipient': 'rezipierende Person; empfangende Person',
        'Rezipienten': 'Rezipierende; Publikum',
        'Richter': 'rechtsprechende Person',
        'Richter': 'Richterschaft',
        'Rollstuhlfahrer': 'Person im Rollstuhl',
        'Sachbearbeiter': 'Verwaltungskraft',
        'Sänger': 'Stimme',
        'Sänger': 'Stimmen; Chor; Personen, die singen; Gesangsgruppe; Singende',
        'Sanitäter': 'Rettungskräfte',
        'Schatzmeister': 'Finanzvorstand; Kassenführung; Kassenverwaltung',
        'Schauspieler': 'Rollen; Besetzung; Darstellende',
        'Schirmherr': 'Support; gefördert/unterstützt von...',
        'Schirmherrschaft': 'Support; gefördert/unterstützt von...',
        'Schlichter': 'Schlichtende; Schlichtungsperson',
        'Schneemann': 'Schneefigur',
        'Schöpfer': 'noch kein passender Begriff gefunden;',
        'Schöpfer': '(Er-)Schaffende',
        'Schulabbrecher': 'Geringqualifizierte; Menschen ohne Schulabschluss',
        'Schuldiger': 'schuldige Person',
        'Schuldige': '[im Plural ist dieses Wort schon gendergerecht]',
        'Schüler': 'Schulkind',
        'Schüler': 'Schulkinder; Kinder; Jugendliche; die Klasse; Lernende; Beschulte',
        'Schüleraustausch': 'Schulaustausch',
        'Schülerbegegnung': 'Schulbegegnung; Klassenbegegnung',
        'Seefahrer': 'Seeleute',
        'Seemann': 'Hochsee-Fachkraft; maritime Fachkraft',
        'seinerzeit': 'zu jener Zeit; damals; einst; früher',
        'seinesgleichen': 'von gleicher Art',
        'Sekretärin': 'Verwaltungskraft; Assistenz; Schreibkraft; Bürokraft',
        'Sekretärinnen': 'Verwaltungskräfte; Verwaltungsfachangestellte; Assistenzen; Schreibkräfte; Bürokräfte',
        'Selbstmörder': 'einen Selbstmord/Suizid begehende Person',
        'Seminarleiter': 'Seminarleitung',
        'Sender': 'gesendet von...',
        'Sender-Nachricht-Empfänger-Modell (Kommunikationsmodell)': 'noch kein passender Begriff gefunden;',
        'Sender': 'Sendende',
        'Senioren': 'ältere Menschen; Menschen im Rentenalter',
        'Sexist': 'sexistische Person',
        'Sieger': 'Erster Platz',
        'Soldat': 'Mitglied der Streitkräfte eines Landes',
        'Sozialarbeiter': 'noch kein passender Begriff gefunden;',
        'Sozialarbeiter': 'Sozialarbeitende',
        'Sozialpädagoge': 'noch kein passender Begriff gefunden;',
        'Spaziergänger': 'Wandersperson',
        'Spaziergänger': 'noch kein passender Begriff gefunden;',
        'Spender': 'Gebende; Sponsoring; Spenden',
        'Spezialisten': 'Sachkundige; Fachleute; Sachverständige',
        'Spieler': 'Teammitglied',
        'Spieler': 'Spielende; Teammitglieder',
        'Spion': 'auskundschaftende Person; spionierende Person',
        'Sprecher': 'Abgeordnete',
        'Sprecher (Radio, Fernsehen, Hörbuch)': 'Stimme; Text gesprochen von; Moderation; Kommentar; Ansage',
        'Sprecher': 'Sprachrohr; Pressestelle; Öffentlichkeitsarbeit',
        'Sponsoren': 'Sponsoring; geldgebende Personen/Firmen',
        'Sportfreunde': 'Mitglieder des/unseres Vereins',
        'Sportler': 'noch kein passender Begriff gefunden;',
        'Sportler': 'Sporttreibende',
        'Staatsbürgerschaft': 'Staatsangehörigkeit; Nationalität',
        'Staatsmänner': 'Volksbeauftragte; Menschen in der Politik',
        'Stadtführer': 'Stadtführung; Reiseleitung',
        'Star': 'berühmte Persönlichkeit; Berühmtheit',
        'Steinewerfer': 'Steinewerfende; Steine werfende Personen',
        'Stellvertreter': 'Stellvertretung',
        'Steuerhinterzieher': 'Steuerhinterziehende',
        'Stifterrat': 'Stiftungsrat',
        'Stifterversammlung': 'Stiftungsversammlung',
        'Stipendiaten': 'Studierende mit Stipendium',
        'Strahlemann': 'Sonnenschein',
        'Student': 'Mitglied der Studierenden',
        'Studenten': 'Studierende',
        'Studienanfänger': 'Studienbeginnende; Erstis; Erstsemestrige',
        'Studienbewerber': 'Studienbewerbungen; Einschreibungen',
        'Tagesmutter': 'Tagespflege(person); Tagesbetreuung; Tageseltern; Kinderbetreuung',
        'Tante-Emma-Laden': 'Minimarkt; Laden für Waren des täglichen Bedarfs',
        'Täter': 'Unrechtsperson',
        'Täter': 'Unrechtspersonen; Tatbegehende; Kriminelle; (Straf-)Tat begangen von...',
        'Teamleiter': 'Teamleitung',
        'Techniker': 'technische Fachkraft',
        'Teilnehmer': 'Teilnehmende; Beteiligte; alle, die an ... teilnehmen; Anwesende; Anmeldungen',
        'Teilnehmergebühr': 'Teilnahmegebühr',
        'Teilnehmerliste': 'Teilnahmeliste; Anwesenheitsliste; Teilnehmendenliste',
        'Teilnehmerzahl': 'Teilnahmezahl; Gruppengröße; Anmeldezahl',
        'Terrorist': 'des Terrors verdächtigte Person; eines Terroranschlags überführte Person',
        'Terroristen': 'Terrorisierende',
        'Testleiter': 'Testleitung',
        'Theaterpädagoge': 'theaterpädagogische Fachkraft',
        'Theoretiker': 'theoretisch Arbeitende',
        'Therapeut': 'therapeutisches Fachpersonal',
        'Touristen': 'Urlaubsgäste',
        'Trainer': 'Übungsleitung',
        'Trainer': 'Referierende; Vortragende; Unterrichtende; Lehrende',
        'Türke': 'türkischer Gemüse-/Obstladen; Laden um die Ecke; kleiner Gemüseladen',
        'Tutor': 'studentische Hilfskraft',
        'Tutoren': 'Übungs(an)leitende; Tutoriumsbegleitende; Ratgebende; Begleitung',
        'übermannen': 'überkommen; überwältigen',
        'Übersetzer': 'Übersetzende; Literatur Übersetzende',
        'Übungsleiter': 'sportliche/technische/praktische Anleitung; anleitende Person',
        'Umschüler': 'Umlernende; Umschulende; die zu Qualifizierenden; Personen in beruflicher Neuorientierung',
        'unbemannt': 'maschinengesteuert; autonom; ferngesteuert; unbesetzt; robotisch',
        'Unternehmer': 'noch kein passender Begriff gefunden;',
        'Unternehmer': 'Selbstständige; Wirtschaftstreibende; Geschäftsleute',
        'Unterstützer': 'support; Geldgebende; Förderung durch ...',
        'Urheber': 'noch kein passender Begriff gefunden;',
        'Urheberrecht': 'Copyright; Recht auf geistiges Eigentum',
        'Urlauber': 'Reisende',
        'User': 'Nutzende; Personen, die Apps/Software nutzen; Mitglieder',
        'V-Mann': 'V-Person',
        'V-Männer': 'V-Leute',
        'Vater': 'Elternteil',
        'Vaterland': 'Heimatland; Geburtsland; Erstland',
        'väterlicherseits': '(vornamen-)licherseits [bei gleichgeschlechtlichen Elternpaaren]',
        'Veranstalter': 'veranstaltet durch/von',
        'Verantwortlicher': 'die Verantwortung tragende Person; verantwortliche Person',
        'Verantwortliche': '[im Plural ist dieses Wort schon gendergerecht]',
        'Verbandsgesellschafter': 'Vertretungen / Beteiligte der Verbände',
        'Verbandsvertreter': 'Vertretungen / Beteiligte der Verbände',
        'Verbraucher': 'Kundschaft; Konsumierende',
        'Verbraucherschutz': 'noch kein passender Begriff gefunden;',
        'Verbraucherschützer': 'für den Verbraucherschutz beauftragte Person',
        'Verbrecher': 'Person, die eine Straftat/ein Verbrechen begeht',
        'Verfasser': 'verfasst von; Autorenschaft',
        'Verkäufer': 'Kaufhauspersonal; Personal',
        'Verkehrssünder': 'Verkehrsregeln missachtende Person',
        'Verkehrsteilnehmer': 'Verkehrsbeteiligte',
        'Verleger': 'Publizierende',
        'Verlierer': 'der letzte Platz',
        'Verlierer': 'die Letzten',
        'Vermieter': 'vermietende Person',
        'Vermittler': 'Mittelsperson',
        'Versichertenkarte': 'Versicherungskarte; Gesundheitskarte',
        'Versichertennummer': 'Versicherungsnummer',
        'Versicherungsnehmer': 'versicherte Person',
        'Versicherungsnehmer': 'versicherte Personen; Versicherte',
        'Versuchsleiter': 'Versuchsleitung',
        'Verteidiger': 'Verteidigung; Rechtsvertretung',
        'Vertragspartner': 'Vertragsparteien',
        'Vertreter': 'in vertretender Position',
        'Vertreter': 'vertreten durch; Vertretung; Delegierte; Abgeordnete; Beauftragte',
        'Verwandter': 'Familienmitglied',
        'Veteran': 'noch kein passender Begriff gefunden;',
        'Vorgesetzter': 'Führungskraft',
        'Vormund': 'die Vormundschaft innehabende Person; Vormundschaft',
        'Vorläufer': 'älteres/altes Modell',
        'Vorreiter': 'Person an der Spitze; Person, die etwas vorlebt; Person, die voraus denkt/handelt',
        'Vorsitzender': 'noch kein passender Begriff gefunden;',
        'Vorstand': 'Vorstandsmitglied; im Vorstand',
        'Wächter': 'Wache',
        'Wähler': 'Wahlberechtigte; alle, die zur Wahl gegangen sind',
        'Wählerinitiative': 'Initiative der Wahlberechtigten',
        'Wählerverzeichnis': 'Wahlverzeichnis',
        'Wart': 'noch kein passender Begriff gefunden;',
        'Wegbereiter': 'Weg bereitende Person(en); prägende Person(en)',
        'Wegewart': 'noch kein passender Begriff gefunden;',
        'weltmännisch': 'cosmopolitisch, weltgewandt',
        'Weltmarktführer': 'Weltmarktführende',
        'Wettbewerber': 'Konkurrenz; Wettbewerbsteilnehmende',
        'Wissenschaftler': 'Forschende; wissenschaftliches Personal der Universität;',
        'Witwer': 'Verwitwete',
        'Workshopleiter': 'Workshopleitung',
        'Zahnarztpraxis': 'Praxis für Zahnerhaltung; zahnmedizinische Praxis; Praxis für Zahnmedizin',
        'Zauberer': 'Zaubertrick vorführende Person',
        'Zauberer': 'Zauberkunstschaffende',
        'Zehnkämpfer': 'am Zehnkampf teilnehmende Person',
        'Zeitgenosse': 'Mitmensch',
        'Zeuge': 'bezeugende Person',
        'Zeugen': 'Bezeugende',
        'Zimmermädchen': 'Servicekraft; Raumpflege; Reinigungskraft',
        'Zuhörer': 'Publikum; Auditorium',
        'Zuschauer': 'Person aus dem Publikum',
        'Zuschauer': 'Publikum',
        'Zuständiger': 'zuständige Person',
        'Zuwanderer': 'Zugewanderte; Personen mit Migrationshintergrund; Eingewanderte; Migrierte'
    };
        var textDiv = self.getTextDiv();
        var textContent = self.getText();
        textContent = textContent.replace(/[\W]+/g," ");
        var ungenderedWords = [];
        self.log("textField: " + textDiv);
        self.log("text: " + textContent);

        var words = textContent.split(" ");
        for (var i = 0; i < words.length; i += 1) {
            self.log("checking word: "+words[i]);
            if(words[i] != "" && words[i] != " " && words[i] in genderMap)
            {
                self.log("found ungendered word: "+words[i]);
                if($.inArray(words[i],ungenderedWords)<0)
                {
                    ungenderedWords.push(words[i]);
                }
            }
        }
        if(ungenderedWords.length>0)
        {
            self.injectRedOutputField();
            self.getOutputField().text("Ungendered Words found: "+ungenderedWords);
        }
        else
        {
            self.injectGreenOutputField();
            self.getOutputField().text("No gendering issues found");
        }
    };

    self.injectRedOutputField = function () {
        var el = $('.new_word_count');
        var log = $('#GenderOutput');
        if (log.length) {
            el = log;
        }
        el.before('<div id="GenderOutput" style="color: red; font-weight: bold; font-size: 14pt; padding: 8px 0px;"></div>');
    };

    self.injectGreenOutputField = function () {
        var el = $('.new_word_count');
        var log = $('#GenderOutput');
        if (log.length) {
            el = log;
        }
        el.before('<div id="GenderOutput" style="color: green; font-weight: bold; font-size: 14pt; padding: 8px 0px;"></div>');
    };

    self.getOutputField = function () {
        return $('#GenderOutput');
    };

    self.getTextDiv = function () {
        return $(".trix-content").find('div');
    };

    self.getText = function () {
        return $(".trix-content").find('div').text();
    };

    self.log = function (message) {
        console.log(message);
    };


    // Initialize the script
    self.init();
})();
