// ==UserScript==
// @name       Aurora Gender Highlighter
// @namespace  lukasPoehn
// @version    0.1.2
// @description  Script to find ungendered Word in your
// @match      https://aurora.iguw.tuwien.ac.at/course/dwi/challenge/*
// @copyright  2018+, Lukas Pöhn
// @require    http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
// @downloadURL https://raw.githubusercontent.com/Blackfreezzer/AuroraGenderHelper/master/genderScript.js
// ==/UserScript==

/*
 Changelog:
 v0.1.2 (Dec. 2018)
 fixed case-matches
 refresh on changes - with debounce
 fix issues with unicode (äüö)
 added gendering check on review-texts
 

 v0.1.1 (2018)
 Initial prototype
 */
var showGenderIssuesOn
(function AuroraGenderHighlighterClass() {
    var self = this;
    var logging = true; //set to true to enable console logs
    var debounceRate = 1000; // the debounce rate on edits in ms
    self.init = function () {
        self.extendJQuery();
        self.detectUngenderendWords();
        document.addEventListener('trix-change',self.onTextChange);
    };

   self.debounce = function(func, wait, immediate) {
	var timeout;
	return function() {
		var context = this, args = arguments;
		var later = function() {
			timeout = null;
			if (!immediate) func.apply(context, args);
		};
		var callNow = immediate && !timeout;
		clearTimeout(timeout);
		timeout = setTimeout(later, wait);
		if (callNow) func.apply(context, args);
      };
    };

    self.onTextChange = self.debounce(function(target)
    {
        self.detectUngenderendWords();
    },debounceRate);

    self.extendJQuery = function () {
        jQuery.fn.justtext = function () {
            return $(this).clone()
                .children()
                .remove()
                .end()
                .text().trim();
        };
    };

    self.detectUngenderendWords = function () {
        var textDiv = self.getTextDiv();
        var textContent = self.getText();
        textContent = textContent.replace(/[\P{L}]+/gu," ");
        var ungenderedWords = [];
        self.log("textField: " + textDiv);
        self.log("text: " + textContent);

        var words = textContent.split(" ");
        for (var i = 0; i < words.length; i += 1) {
            self.log("checking word: "+words[i]);
            if(words[i] != "" && words[i] != " " && words[i].toLowerCase() in genderMap)
            {
                self.log("found ungendered word: "+words[i]);
                if($.inArray(words[i],ungenderedWords)<0)
                {
                    ungenderedWords.push(words[i]);
                }
            }
        }
        if(ungenderedWords.length>0)
        {
            if(!self.getOutputField().length || self.getOutputField().hasClass("green"))
            {
                if (self.getOutputField().length)
                {
                    self.getOutputField().remove();
                }
                self.injectRedOutputField();
            }
            self.getOutputField().text("Ungendered Words found: "+ungenderedWords);
        }
        else
        {
            if(!self.getOutputField().length || self.getOutputField().hasClass("red"))
            {
                if (self.getOutputField().length)
                {
                    self.getOutputField().remove();
                }
                self.injectGreenOutputField();
            }
            self.getOutputField().text("No gendering issues found");
        }
    };

    self.injectRedOutputField = function () {
        var el = $(".trix-content");
        el.after('<div id="GenderOutput" class="red" style="color: red; font-weight: bold; font-size: 14pt; padding: 8px 0px;"></div>');
    };

    self.injectGreenOutputField = function () {
        var el = $(".trix-content");
        el.after('<div id="GenderOutput" class="green" style="color: green; font-weight: bold; font-size: 14pt; padding: 8px 0px;"></div>');
    };

    self.getOutputField = function () {
        return $('#GenderOutput');
    };

    self.getTextDiv = function () {
        return $(".trix-content").find('div');
    };

    self.getText = function () {
        return $(".trix-content").find('div').text();
    };

    self.log = function (message) {
        if(logging){console.log(message);}
    };

    var genderMap = {
        'absender': 'abgesandt durch',
        'absolventen': 'abschluss inhabende person; person mit abschluss',
        'absolventenpraktikum': 'praktikum (direkt) nach studienabschluss',
        'abteilungsleiter': 'abteilungsleitung',
        'abteilungsleitertreffen': 'treffen der abteilungsleitungen',
        'administrator': 'administration; admin',
        'adressat': 'zielperson',
        'agent': 'auskundschaftende person; spionierende person',
        'akademiker': 'studierte',
        'akteure': 'beteiligte; agierende; handelnde',
        'aktionär': 'person mit aktienbesitz',
        'aktionäre': 'aktien-/anteilshabende',
        'aktionärsversammlung': 'versammlung von personen mit aktienbesitz',
        'alkoholiker': 'alkoholsüchtige person; person mit alkoholsucht',
        'alkoholiker': 'alkoholsüchtige; menschen mit alkoholsucht',
        'altenpfleger': 'pflegefachkraft',
        'ampelmännchen': 'ampelfiguren; ampelfigürchen; ampelmenschlein',
        'anbieter': 'angebot (von...); herstellung; angebotsstellende person; angebotsmachende person',
        'andere': 'gegenüber',
        'anfänger': 'unerfahrene; menschen ohne vorkenntnisse; menschen ohne vorerfahrung; beginnende',
        'das angebot richtet sich an anfänger und fortgeschrittene.': '... das angebot richtet sich an personen mit und ohne vorkenntnisse.',
        'anfängerkurs': 'einstiegskurs; grundkurs; kurs für menschen ohne vorkenntnisse; kurs für menschen ohne vorerfahrung',
        'angehöriger': 'familienmitglied',
        'angeklagter': 'angeklagte person',
        'anhänger': 'fans; begeisterte',
        'anhänger': 'gleichgesinnte; unterstützende; sympathisierende; sich [einer bewegung] zuordnende',
        'animateur': 'freizeitbetreuungsperson',
        'sprachanimateur': 'noch kein passender begriff gefunden;',
        'animateure': 'animierende',
        'anleger': 'anlegende',
        'anleiter': 'anleitende person',
        'ansprechpartner': 'ansprechperson; kontakt',
        'antragsteller': 'beantragende person/einrichtung; die person, die einen antrag stellt; die antragstellende person; antrag gestellt von ...',
        'antragsteller werden in kürze benachrichtigt.': '... sie werden kurz nach antragstellung benachrichtigt.',
        'anwalt': 'rechtsbeistand',
        'anwaltskosten': 'kosten für die rechtsvertretung',
        'anwender': 'nutzende; anwendende; personen, die ... anwenden; anwendung',
        'anwenderbezogen': 'anwendungsbezogen; praxisbezogen',
        'anwohner': 'alle, die in dieser straße wohnen; anwohnende; nachbarschaft',
        'apotheker': 'arzneikundige',
        'fragen sie ihren arzt oder apotheker.': '... holen sie sich ärztlichen oder pharmazeutischen rat. / holen sie sich bei fragen ärztlichen rat oder erkundigen sie sich in ihrer apotheke.',
        'arbeiter': 'arbeitskraft',
        'arbeiter': 'erwerbstätige; belegschaft; beschäftigte',
        'arbeitgeber': 'führungskraft',
        'arbeitgeber': 'arbeitgebende; betriebe; unternehmen',
        'das ist ein aspekt, der für seine späteren arbeitgeber interessant ist.': '... das ist ein aspekt, der für ihn im späteren bewerbungsprozess von vorteil ist.',
        'arbeitnehmer': 'beschäftigte; arbeitskräfte; belegschaft; personal',
        'architekten': 'architekturschaffende',
        'arzt': 'person im ärztlichen dienst; ärztliches fachpersonal',
        'ärzte': 'ärztliches (fach-)personal',
        'arztbesuch': 'ärztlicher kontakt; ärztliche sprechstunde; besuch der ärztlichen sprechstunde; ärztliche visite',
        'arztbrief': 'entlassungsbrief; entlassbericht; ärztlicher/medizinischer (abschluss-)bericht; ärztliche epikrise; ärztlicher brief; (ärztlicher) befundbericht; ärztliches informationsschreiben; ärztliche information',
        'arztgeheimnis': 'ärztliche schweigepflicht',
        'arzthelferinnen': 'medizinische fachangestellte',
        'arztkoffer /-köfferchen': 'behandlungstasche; medizinkoffer /-köfferchen',
        'arztkosten': '(ärztliche) behandlungskosten',
        'arzt-patienten-verhältnis': 'noch kein passender begriff gefunden;',
        'arztpraxis': 'praxis für ...-medizin (z.b. praxis für allgemeinmedizin); ärztliche praxis',
        'arzttermin': 'behandlungstermin; vorsorgetermin',
        'arztwahl': 'wahl des ärztlichen fachpersonals',
        'assistent': 'assistenz',
        'assistenzarzt': 'person in fachärztlicher weiterbildung; ärztliches fachpersonal in weiterbildung',
        'asylbewerber': 'asylsuchende; personen im asylverfahren',
        'athlet': 'sporttreibende person',
        'athleten': 'sporttreibende; wettkämpfende',
        'attentäter': 'person, die ein attentat verübt',
        'auftraggeber': 'auftraggebende; auftraggebende personen; in auftrag gegeben von... ; beauftragt von...',
        'auftragnehmer': 'einen auftrag entgegen nehmende / annehmende person',
        'augenoptiker (geschäft mit werkstatt)': 'optikfachgeschäft',
        'ausländer': 'person aus dem ausland; person nichtdeutscher herkunft; ausländische person; person mit anderer staatsangehörigkeit',
        'ausländerbehörde': 'migrationsamt/-stelle; zuwanderungsamt/-stelle',
        'aussiedler': 'ausgesiedelte person',
        'aussiedler': 'ausgesiedelte personen',
        'aussteller': 'noch kein passender begriff gefunden;',
        'ausstellerausweis': 'noch kein passender begriff gefunden',
        'ausstellerliste': 'noch kein passender begriff gefunden',
        'auszubildender': 'nachwuchskraft; person in ausbildung; auszubildende person; lernende person',
        'auszubildende': '[im plural ist dieses wort schon gendergerecht]',
        'autor': 'bücherschreibende person',
        'autoren': 'autorenschaft; urheberrechtsinhabende; verfassende; schreibende; literaturschaffende',
        'bankräuber': 'bankausraubende',
        'bauarbeiter': 'bauarbeiten ausführendes (fach-)personal',
        'bauern': 'landwirtschaft betreibende; landwirtschaftlich beschäftigte; beschäftigte in der landwirtschaft',
        'bauherr': 'den bau in auftrag gebende person',
        'bauherren': 'bauende',
        'beamter': 'verbeamtete person; person im beamtenstatus; der/die beamte (kurzform von der/die beamtete)',
        'beamtenlaufbahn': 'verbeamteter werdegang; laufbahn im öffentlichen dienst mit aussicht auf verbeamtung',
        'bearbeiter': 'den vorgang betreuende person; zuständige person',
        'beauftragter': 'beauftragte person',
        'bediener': 'bedienende person',
        'befragter': 'befragte person; person, die befragt wurde',
        'befürworter': 'unterstützung; zustimmende',
        'behinderter': 'mensch mit behinderung',
        'beisitzer': 'beisitzende',
        'bekannter': 'person aus dem bekanntenkreis; (mir) bekannte person; bekanntschaft',
        'bemannt': 'besetzt; mit personen besetzt; astronautisch',
        'bemuttern': 'fürsorglich sein, verhätscheln, umsorgen',
        'benutzer': 'anwendende; nutzende',
        'benutzerfreundlich': 'praktisch / leicht zu bedienen; bedienungsfreundlich; benutzungsfreundlich',
        'benutzername': 'nickname; pseudonym',
        'benutzeroberfläche': 'bedienoberfläche; benutzungsoberfläche',
        'benutzerordnung': '(be-)nutzungsordnung',
        'beobachter': 'beobachtende',
        'berater': 'beratende person; die beratung erfolgt durch... ; sie werden beraten von ...',
        'beratertätigkeit': 'beratende tätigkeit, beratung',
        'bergmännisch': 'berichterstatter bericht erstattende person',
        'berichterstatter': 'berichtende',
        'berliner': 'die berliner bevölkerung',
        'berufsanfänger': 'berufsunerfahrene',
        'beschäftigter': 'arbeitskraft',
        'beschuldigter': 'beschuldigte person',
        'besitzer': 'besitzhabende person',
        'besitzer von immobilieneigentum': 'immobilien besitzende person',
        'besucher': 'gäste* (*siehe anmerkung unter gäste); publikum; besuche',
        'besuchergruppe': 'besuchsgruppe',
        'betrachter': 'betrachtende',
        'betreiber': 'betriebsgesellschaft; betreibende firma',
        'betreuer': 'betreuungsperson',
        'betriebsrat': 'mitglied des betriebsrates',
        'betriebsräte': 'mitglieder des betriebsrates; der betriebsrat; mitarbeitendenvertretung; der personalrat',
        'betroffener': 'betroffene person; opfer',
        'bewerber': 'sich bewerbende person',
        'bewerber': 'bewerbende; sich bewerbende personen',
        'bewerberzahlen': 'bewerbungszahlen',
        'bewohner': 'in ... lebende; in ... lebende menschen',
        'blockwart': 'noch kein passender begriff gefunden',
        'blogger': 'bloggende personen; personen, die einen blog schreiben',
        'briefträger': 'briefzustellung; postzustellung',
        'brüderlichkeit': 'mitmenschlichkeit; solidarität',
        'buhmann': 'sündenbock; feindbild',
        'bundespräsidentenwahl': 'bundespräsidentschaftswahl; bp-wahl',
        'bürger': 'mitglied des staates / der stadt;',
        'bürger': 'bevölkerung; einwohnerschaft; (kommunal-)wahlberechtigte; staatsangehörige; einheimische; im ort/in der stadt ... wohnende',
        'bürgermeister': 'stadtoberhaupt',
        'bürgerrechte': 'rechte des deutschen (oder anderer staaten) staatsvolkes',
        'bürgersteig': 'gehweg; fußweg',
        'bürgerzentrum': 'kulturzentrum; stadtteilzentrum; selbstverwaltetes zentrum',
        'busfahrer': 'busführung; busführende person',
        'chef': 'vorgesetzte person; leitungsperson; leitung',
        'chefs': 'vorgesetzte; leitung',
        'chefsache': 'sache mit oberster priorität; angelegenheit mit besonderer wichtigkeit; dringliche sache',
        'chemiker': 'fachkraft für chemie',
        'chirurgenstahl': 'chirurgiestahl',
        'christen': 'menschen christlichen glaubens',
        'coach': 'begleitung; beratung',
        'damenprogramm': 'begleitprogramm',
        'dekan': 'leitung des dekanats; dekanat',
        'demonstranten': 'demonstrierende',
        'designer': 'designschaffende',
        'deutscher': 'person aus deutschland; deutsche person; person mit deutscher staatsangehörigkeit',
        'dienstherrengenehmigung': 'vorgesetztengenehmigung',
        'dienstleister': 'dienstleistende person; dienstleistendes unternehmen',
        'diplomingenieur': 'diplomierte technische fachkraft',
        'geschlecht, 2013': '... anteil von forschenden und diplomierten technischen fachkräften an der gesamtarbeitskraft nach geschlecht, 2013',
        'dirigent': 'unter dem dirigat von ...; unter leitung von dj der/die dj',
        'doktoranden': 'promovierende',
        'doktorandenkolleg': 'promotionskolleg; promovierendenkolleg',
        'dolmetscher': '(simultan-)übersetzende fachkraft',
        'dönermann': 'dönerbude; kebapverkauf.',
        'dozent': 'lehrende person; lehrkraft; lehrperson; vortragende person',
        'dozenten': 'dozierende; lehrpersonal; lehrende',
        'dozententätigkeit': 'lehrtätigkeit',
        'ehegatten': 'eheleute',
        'ehepartner': 'geehelichte person',
        'ehrenamtler': 'ehrenamtliche; freiwillige; (ehrenamtlich) engagierte',
        'ehrenmann': 'ehrenperson',
        'eigentümer': '(im) eigentum von ...',
        'ein-mann-betrieb': 'ein-personen-betrieb',
        'einsteigerkurs': 'einstiegskurs; grundlagenkurs; grundkurs; basiskurs',
        'einwanderer': 'menschen mit migrationshintergrund /-geschichte /-biografie',
        'einwohner': 'die menschen der stadt xy; population; bevölkerung',
        'einzelne': '[im plural ist dieses wort schon gendergerecht]',
        'empfänger': 'empfangen von... ; für... ; bestimmt für...',
        'enkel': 'enkelkind',
        'entdecker': 'entdeckt von ...',
        'entdecker': 'entdeckt von ... ; entdeckende personen /kinder; forschende; entdeckende',
        'entscheidungsträger': 'person mit entscheidungsbefugnis',
        'entwickler': 'entwickelnde; erfindende',
        'erben': 'erbberechtigte',
        'ermittler': 'ermittelnde; ermittlungsteam',
        'erstsemester': 'studierende im ersten semester',
        'erzieher': 'pädagogische fachkraft; erziehungskraft',
        'experte': 'fachgröße; autorität; koryphäe; person vom fach',
        'experten': 'fachkräfte; fachleute; fachkundige; sachverständige',
        'expertengruppe': 'fachgruppe',
        'expertentagung': 'fachtagung',
        'expertenwissen': 'fachwissen; expertise',
        'facharzt': 'ärztliche fachkraft',
        'fachmann': 'fachkraft',
        'fachmännisch': 'fachkundig',
        'fachwissenschaftler': 'fachforschende',
        'fahrer': 'fahrdienst',
        'fahrer': 'fahrzeugführende; fahrende',
        'fahrgast': 'mitreisende person; gegen entgelt transportierte person',
        'fahrgäste': 'mitfahrende; reisende',
        'fahrradfahrer': 'fahrrad fahrende; wer mit dem fahrrad unterwegs ist...',
        'fahrzeughalter': 'eine ein fahrzeug besitzende person',
        'familienhelfer': 'familienhilfe; familien unterstützende (fach-)kraft; die die familie x. unterstützende fachperson/fachkraft; im familienunterstützenden dienst arbeitende / angestellte person',
        'fan': 'in besonderem maße begeisterte person',
        'fans': 'begeisterte',
        'favorit': 'favorisierte (antretende) person; favorisierte option',
        'feind': 'noch kein passender begriff gefunden;',
        'feuerwehrmänner': 'einsatzkräfte der feuerwehr; feuerwehrangehörige; feuerwehr; feuerwehrleute',
        'filmemacher': 'filmschaffende person',
        'filmemacher': 'filmschaffende',
        'filmstar': 'filmgröße; filmberühmtheit',
        'finanzintermediäre': 'anbietende von finanzintermediation; finanzintermediierende',
        'flüchtlinge': 'geflüchtete; flüchtende; geflüchtete menschen',
        'förderer': 'stelle, die fördermittel vergibt',
        'förderer': 'unterstützender personenkreis',
        'fördermittelgeber': 'stelle, die fördermittel vergibt; fördermittelgebende stelle',
        'forscher': 'forschende; universitätsmitglieder; wissenschaftliches personal der universität; menschen, die in der forschung tätig sind; forschungsteam',
        'forschergemeinde': 'forschungsgemeinde',
        'forscherkolloquium': 'forschungskolloquium',
        'forscherteam': 'forschungsteam',
        'fortgeschrittene': '[im plural ist dieses wort schon gendergerecht]',
        'fotograf': 'noch kein passender begriff gefunden',
        'fotografen': 'fotografierende; aufnehmende',
        'freund': '(enge) bezugsperson; herzensmensch; bekanntschaft',
        'freunde': 'bekannte; bezugspersonen',
        'führerschein': 'fahrerlaubnis; fahrberechtigung',
        'funktionär': 'in funktion gewählte person; verantwortliche/beauftragte/bevollmächtigte person',
        'funktionsträger': 'in funktion gewählte person; verantwortliche/beauftragte/bevollmächtigte person',
        'fußballspieler': 'fußballspielende',
        'fußgänger': 'menschen zu fuß; zu fuß gehende',
        'fußgängerstreifen': 'zebrastreifen',
        'fußgängerweg': 'gehweg',
        'fußgängerzone': 'flanierzone; einkaufsstraße; verkehrsfreie zone; verkehrsberuhigter bereich',
        'gärtner': 'gartenarbeitskraft',
        'gast': 'besuch; besuchsperson',
        'gastbeitrag': 'sonderbeitrag',
        'gäste': 'eingeladene, geladene, besuchefinden.]',
        'gastgeber': 'einladende',
        'gasthörer': 'studierende im gaststudium',
        'gasthörerstatus': 'gaststudierendenstatus',
        'gasthörerstudium': 'gaststudium; hospitation',
        'geisterfahrer': 'fahrzeug in falscher richtung',
        'geldgeber': 'geldgebende; support',
        'generaldirektor': 'direktoriumsleitung',
        'generalist': 'universalgenie; multitalent; weitere alternativen gesucht für generalist als gegensatz zu spezialist;',
        'geograph': 'noch kein passender begriff gefunden',
        'geologe': 'noch kein passender begriff gefunden',
        'gerätewart': 'geräteaufsicht',
        'geschäftsführer': 'geschäftsführung; geschäftsleitung',
        'geschäftsmänner': 'geschäftsleute',
        'geschäftspartner': 'geschäftliche verbindung',
        'gesellschafter': 'betriebsgesellschaft',
        'gesetzgeber': 'legislative; gesetzgebende instanz; gesetzgebende',
        'gesprächspartner': 'gesprächsbeteiligte; gegenüber',
        'gewinner': 'erster platz',
        'gläubiger': 'geld-/kreditgebende',
        'götter': 'allwissende; allmächtige; übernatürliche wesen; ewige; gottheiten',
        'grinsepeter': 'grinsebacke; grinsegesicht; grinsekuchen',
        'gründer': 'gründende person',
        'gründerzeit': 'gründungszeit',
        'gruppenleiter': 'gruppenleitende; gruppenleitung',
        'gutachter': 'begutachtet von ...',
        'gutachter': 'sachverständige',
        'hacker': 'personen, die fremde digitaldaten nutzen; hackende; ',
        'hackerangriff': 'hackingangriff; hackangriff',
        'hamburger': 'die hamburger bevölkerung',
        'handwerker': 'noch kein passender begriff gefunden;',
        'handwerker': 'handwerksbetriebe',
        'hausherr': 'familienvorstand; hausvorstand',
        'hausmeister': 'gebäudemanagement',
        'hebammen': 'geburtshelfende',
        'held': 'schlüsselperson; hauptperson; außerordentlich erfolgreiche person',
        'helfer': 'hilfskraft; assistenz',
        'helfer': 'helfende',
        'herausgeber': 'herausgegeben von ...',
        'herrscher': 'staatsoberhaupt',
        'hersteller': 'herstellfirma',
        'hexe': '(schwarze) zauberkraft innehabende person; person mit (schwarzen) zauberkräften; mit zauberkräften ausgestattete person',
        'ich-erzähler': 'ich-form; ich-figur; erzählendes ich',
        'immigranten': 'menschen mit migrationshintergrund /-geschichte /-biografie',
        'immobilienbesitzer': 'immobilienbesitzende',
        'individuum': '[als neutrum ist dieses wort schon gendergerecht  das individuum]',
        'informant': 'informationsquelle; quelle',
        'informatiker': 'auf den it-bereich spezialisierte person',
        'ingenieurberuf': 'ingenieursberuf',
        'ingenieure': 'noch kein passender begriff gefunden;',
        'ingenieurwesen': 'technikwissenschaften; technische wissenschaften; technik',
        'inhaber': 'etwas innehabende person',
        'initiatoren': 'initiierende',
        'investoren': 'investierende',
        'interessenten': 'interessierte',
        'interviewer': 'interviewende person',
        'interviewer': 'interviewende',
        'interviewpartner': 'interviewte',
        'jäger': 'jagende person; person auf der jagd',
        'jäger': 'jägerschaft; jagende personen; personen auf der jagd',
        'jeder': 'alle; alle für sich',
        'jedermann': 'alle',
        'jemand, der ...': 'eine person, die ...; ein mensch, der ...',
        'journalist': 'presse; medien; jemand von der presse/vom fernsehen/...; wer für die zeitung/fürs fernsehen berichtet',
        'journalisten': 'im journalismus tätige/arbeitende; medienschaffende; presse; die medien',
        'juden': 'menschen jüdischen glaubens; jüdische menschen; mitglieder / angehörige der jüdischen gemeinschaft / des jüdischen volkes',
        'jugendlicher': 'junge person; junger mensch; teenie; teen; teenager',
        'kameramänner': 'kamerateam',
        'kandidaten': 'kandidierende',
        'kandidatenfragen': 'personalfrage; k-frage',
        'kandidatenvorschlag': 'personalvorschlag',
        'kanzler': 'regierung (an-)führende person; regierungsoberhaupt',
        'kanzleramt': 'noch kein passender begriff gefunden;',
        'kassierer': 'person an der kasse',
        'katholiken': 'menschen katholischen glaubens',
        'kaufmännisch': 'zahlentechnisch; finanztechnisch; in zahlen gesehen',
        'keiner': 'niemand',
        'kellner': 'servicekraft; bedienung',
        'kinderarztpraxis': 'praxis für kinderheilkunde',
        'kindermädchen': 'kinderbetreuung; aupair',
        'kläger': 'klagende person',
        'kleinbauern': 'kleine landwirtschaftsbetriebe',
        'klient': 'ratsuchende person; beratung in anspruch nehmende person; person, die in die beratung kommt; fall; besuch',
        'klienten': 'klientel',
        'klientenorientiert': 'orientiert am bedarf der ratsuchenden person',
        'kollegen': 'kollegschaft; kollegium',
        'kommentator': 'kommentierender pressemensch; kommentierende presse',
        'kommentatoren': 'kommentar von medienschaffenden',
        'kommilitonen': 'mitstudierende',
        'komponist': 'musikschaffende person; kompositionstätige person',
        'komponisten': 'musikschaffende; kompositionstätige',
        'konfirmand': 'noch kein passender begriff gefunden;',
        'konfirmanden': 'jugendliche in der konfirmationsvorbereitung',
        'konfirmandenunterricht': 'konfirmationsunterricht',
        'kontrahent': 'gegenüber',
        'kontoinhaber': 'kontoinhabende person',
        'konkurrent': 'konkurrenz',
        'konsumenten': 'konsumierende; kundschaft; einkaufende / konsumierende zielgruppe',
        'kooperationspartner': 'in kooperation mit',
        'koordinator': 'koordination',
        'krankenschwester': 'pflegefachkraft',
        'krankenschwestern': 'pflegepersonal; beschäftigte in der krankenpflege',
        'kreditnehmer': 'kreditnehmende person',
        'kreditnehmer': 'kreditnehmende',
        'kritiker': 'kritisierende; kritische; kritische stimmen',
        'küchenhelfer': 'küchenhilfe',
        'kunde': 'kundschaft',
        'kundenauftrag': 'auftrag durch kundschaft; auftrag',
        'kundenbedürfnisse': 'bedürfnisse der kundschaft',
        'kundenberatung': 'beratung der kundschaft',
        'kundenfreundlich': 'praktisch zu bedienen; publikumsfreundlich; nutzungsfreundlich',
        'kundenorientiert': 'publikumsorientiert',
        'kundenwerbung': 'akquise',
        'kundenwünsche': 'wünsche der kundschaft',
        'kunstfreunde': 'kunstbegeisterte',
        'künstler': 'kunstschaffende',
        'künstlername': '(künstlerisches) pseudonym; kunstname',
        'laborant': 'laborfachkraft',
        'laborarbeiter': 'laborfachkraft',
        'laie': 'mensch ohne fachkenntnisse; fachunkundige person; fachfremde person',
        'laien': 'fachunkundige; fachfremde',
        'landsmänner': 'landsleute',
        'landwirte': 'landwirtschaft betreibende; landwirtschaftlich beschäftigte; beschäftigte in der landwirtschaft',
        'lehrer': 'lehrperson',
        'lehrer': 'lehrkräfte; lehrpersonen; das kollegium; lehrende',
        'lehrerpult': 'tisch/pult der lehrkraft',
        'lehrerzimmer': 'arbeitszimmer der lehrkräfte; teamraum',
        'lehrling': 'nachwuchskraft; person in ausbildung; auszubildende person; lernende person',
        'lehrlinge': 'auszubildende; lernende',
        'lehrstuhlinhaber': 'leitung des lehrstuhles',
        'lehrstuhlinhaber': 'leitende eines lehrstuhles',
        'lehrstuhlleiter': 'leitung des lehrstuhls',
        'lehrstuhlleiter': 'leitende eines lehrstuhles',
        'leistungsbezieher': 'leistung beziehende',
        'leiter': 'leitung',
        'lektor': 'noch kein passender begriff gefunden',
        'lektorstelle': 'lektoratsstelle',
        'leser': 'leserschaft; lesende zielgruppe',
        'leserbrief': 'kommentar zum artikel xy',
        'leserbriefe': 'ihre kommentare/meinungen; offene zuschriften',
        'leserfreundlich': 'lesefreundlich',
        'lieber': 'an ...; hallo ...; guten tag lieferant lieferfirma',
        'literaturkritiker': 'literatur kritisierende person',
        'literaturkritiker': 'literaturkritisierende',
        'mädchen für alles': 'mensch für alles',
        'mädchenname': 'geburtsname',
        'magier': 'zauberkunst ausübende person',
        'man': 'sie; viele; wir; ich',
        'manager': 'management; unternehmensführung; führungskraft',
        'männchen': 'figürchen; spielfigur',
        'manndeckung': '1 1-verteidigung; (weitere alternativen gesucht ',
        'mannsbild': 'gestandene person, powermensch',
        'mannschaft': 'team; gruppe; kollektiv',
        'mathematiker': 'mathematisch qualifizierte person; sich mit mathematik befassende person',
        'matrose': 'mitglied der schiffsbesatzung',
        'medienanbieter': 'medienorganisationen',
        'medienpartner': 'in medienpartnerschaft mit',
        'mediziner': 'medizinisches/ärztliches fachpersonal',
        'meisterschaft': 'turnier; wettbewerb',
        'mentor': 'vorbild; fürsprechende person; beratende person; fördernde person',
        'mieter': 'mietperson; mietpartei',
        'mieterverein': 'mietverein; mietvertretung',
        'migrant': 'person mit migrationshintergrund; eingewanderte person; der/die migrierte',
        'migranten': 'personen mit migrationshintergrund; eingewanderte; zugewanderte; migrierte',
        'mitarbeiter': 'mitarbeitende; beschäftigte; angestellte; tätige; belegschaft; arbeitskräfte; kollegium; personal; teammitglieder; werktätige; betriebs-/konzern-/firmen-/unternehmensangehörige; bei uns beschäftigte',
        'mitarbeiterführung': 'personalmanagement; personführung; personalpolitik',
        'mitarbeitergespräch': 'dienstbesprechung; qualifikationsgespräch; arbeitsgespräch; beurteilungsgespräch; jahresgespräch; beschäftigtengespräch; personalgespräch',
        'mitarbeiterstellen': 'stellen für mitarbeitende; arbeitsplätze',
        'mitbewohner': 'wohnungsteilende',
        'mitbürger': 'mitmensch',
        'mitbürger': 'landsleute; mitmenschen; staatsangehörige',
        'mitfahrergelegenheit': 'mitfahrgelegenheit',
        'mitglied': '[als neutrum ist dieses wort schon gendergerecht das mitglied]',
        'mitglieder': '[als neutrum ist dieses wort schon gendergerecht  das mitglied - die mitglieder ; wer dennoch eine alternative bevorzugt, kann diese hier nutzen ] zugehörige; angehörige; teil von ...',
        'mitschüler': 'andere kinder aus der klasse / schule',
        'mitwisser': 'eingeweihte',
        'moderator': 'moderation',
        'modeschöpfer': 'mode schaffende',
        'mofafahrer': 'mofa fahrende',
        'mörder': 'einen mord begehende person; mordende person',
        'multiplikator': 'person, die informationen/wissen weitergibt; wissen/informationen weitergebende person',
        'münchner': 'die münchner bevölkerung',
        'musiker': 'musikausübende; musikschaffende; musikspielende; musizierende; mitglieder eines orchesters',
        'muslim': 'mensch muslimischen glaubens',
        'mutter': 'elternteil',
        'mutter-kind-gruppe': 'eltern-kind-gruppe',
        'mütterberatung': 'elternberatung',
        'mütterlicherseits': '(vornamen-)licherseits [bei gleichgeschlechtlichen elternpaaren]',
        'muttermilch': 'elternmilch; brustmilch [z.b. bei transgeschlechtlichen, stillenden vätern]',
        'mutterschutz': 'elternschutz [auch transgeschlechtliche väter haben anspruch auf mutterschutz]',
        'muttersprache': 'heimatsprache; familiensprache; erstsprache',
        'nachbarn': 'nebenan wohnende',
        'nachbarn (in einem wohnhaus; pl.)': 'hausgemeinschaft',
        'nachfolger': 'nachfolge',
        'nachwuchswissenschaftler': 'wissenschaftlicher nachwuchs',
        'namensvetter': 'gleichnamige',
        'nutzer': '(be-)nutzende person; person, die ... nutzt',
        'nutzer': 'personen, die ... nutzen; nutzung; mitglieder; nutzende',
        'oberarzt': 'ärztliche führungskraft',
        'ombudsmann': 'ombudsperson',
        'opfer': '[als neutrum ist dieses wort schon gendergerecht das opfer; eine gendergerechte alternative ist nicht erforderlich]',
        'organisatoren': 'organisation; organisationsteam/-komitee; organisiert von ...; organisierende',
        'organspender': 'organ spendende; organ spendende personen',
        'pächter': 'pachtende person',
        'pädagoge': 'pädagogische fachkraft',
        'paketbote': 'paketzustellung',
        'parlamentarier': 'abgeordnete',
        'partner': 'gegenüber',
        'partner': 'unterstützung; mitglied; beteiligte; kooperationen; partnerorganisationen',
        'partnerarbeit': 'zweierarbeit; paararbeit; tandemarbeit',
        'partnerschaft': 'beziehung; kooperation; zusammenarbeit; tandem',
        'passagier': 'noch kein passender begriff gefunden;',
        'passagiere': 'reisende',
        'passanten': 'vorübergehende',
        'passantenbefragung': 'straßenbefragung',
        'pate': 'patenamt; patenschaft',
        'patienten': 'zu behandelnde personen; personen, die in (ärztlicher) behandlung sind; kranke; erkrankte; menschen mit einer erkrankung; menschen, die im krankenhaus liegen; betroffene; behandelte',
        'patientenkontakt': 'noch kein passender begriff gefunden;',
        'patientenschulung (in der psychologie)': 'noch kein passender begriff gefunden',
        'patientenorientiert': 'noch kein passender begriff gefunden',
        'patientenverfügung': 'verfügung(en) für betreuende personen',
        'patientenversorgung': 'ärztliche versorgung; behandlung; pflege',
        'patientenzimmer': 'noch kein passender begriff gefunden;',
        'pendler': 'pendelnde',
        'pendlerpauschale': 'pendelpauschale; pauschale für pendelnde; pauschale für menschen, die pendeln',
        'personalleiter': 'personalleitung',
        'personalrat': 'mitglied des personalrates',
        'personalräte': 'mitglieder des personalrates; der personalrat; mitarbeitendenvertretung',
        'personalvertreter': 'personalvertretung',
        'pfadfinder': 'scout;',
        'pfarrer': 'pfarrperson',
        'pilot': 'flugzeugführende belegschaft',
        'pionier': 'vorkämpfende person',
        'planer': 'planende personen; planende institutionen',
        'politiker': 'menschen in der politik; menschen, die in der politik tätig sind',
        'polizisten': 'polizei; polizeikräfte; polizeileute',
        'postbote': 'postzustellung',
        'praktikant': 'eine ein praktikum absolvierende person; eine person im praktikum; eine sich in einem praktikum(verhältnis) befindende person',
        'praktikanten': 'auszubildende im praktikum',
        'praktikantenstelle': 'praktikumsstelle',
        'praktiker': 'praktizierende; leute aus der praxis; praktisch veranlagte menschen',
        'präsident': 'staatsoberhaupt; vorsitz',
        'präsidenten': 'vorsitzende',
        'präsidentenwahl': 'präsidentschaftswahl',
        'prediger': 'predigende',
        'preisträger': 'ausgezeichnete person',
        'proband': 'testperson; versuchsperson',
        'probanden': 'testpersonen; versuchspersonen; teilnehmende',
        'produzent': 'die produktionsleitung innehabende person',
        'produzenten': 'produzierende; produktionsteam',
        'professor': 'eine professur innehabende person',
        'professoren': 'professorenschaft',
        'profi': 'fachperson; person mit fachwissen/fachkenntnis',
        'profis': 'sachkundige; fachleute; sachverständige',
        'projektleiter': 'projektleitung',
        'projektträger': 'noch kein passender begriff gefunden',
        'proletarier': 'lohnabhängige; werktätige; arbeitende; angehörige des proletariats',
        'protagonist': 'hauptperson; hauptfigur; zentrale gestalt; schlüsselfigur; titelrolle',
        'protokollführer': 'protokollführende person',
        'prüfer': 'prüfungsleitung; prüfungsabnahme durch...; geprüft von...',
        'prüfling': 'zu prüfende person',
        'psychotherapeut': 'psychotherapeutisches fachpersonal',
        'putzfrau': 'reinigungspersonal; reinigungskraft; raumpflege',
        'rabbiner': 'mitglied des rabbinats',
        'rabbiner': 'rabbinat',
        'radfahrer': 'rad fahrende; wer mit dem rad unterwegs ist...',
        'ratgeber': 'wegbegleitung; beistand; ratgebende/beratende person',
        'raucherbereich': 'bereich für rauchende',
        'raucherpause': 'zigarettenpause',
        'rechnungsprüfer': 'rechnungsprüfung; person, die die rechnungsprüfung macht; person, die für die rechnungsprüfung verantwortlich ist',
        'rechtsanwalt': 'rechtsbeistand',
        'redakteur': 'redaktion; redationsmitglied',
        'rednerliste': 'redeliste',
        'rednerpult': 'redepult',
        'referent': 'referierende person',
        'referenten': 'referierende; vortragende',
        'regierungschef': 'staatsoberhaupt (nur in manchen fällen möglich); noch kein passender begriff gefunden;',
        'reiseleiter': 'reiseleitung',
        'rekrut': 'nachwuchs (der grundausbildung in der bundeswehr)',
        'rektor': 'schulleitung',
        'rentner': 'menschen, im rentenalter; menschen, die in der rente sind',
        'reporter': 'presse; berichterstattende person; medienvertretung',
        'repräsentanten': 'vertretung',
        'rettungsschwimmer': 'aus dem wasser rettende person',
        'rezipient': 'rezipierende person; empfangende person',
        'rezipienten': 'rezipierende; publikum',
        'richter': 'rechtsprechende person',
        'richter': 'richterschaft',
        'rollstuhlfahrer': 'person im rollstuhl',
        'sachbearbeiter': 'verwaltungskraft',
        'sänger': 'stimme',
        'sänger': 'stimmen; chor; personen, die singen; gesangsgruppe; singende',
        'sanitäter': 'rettungskräfte',
        'schatzmeister': 'finanzvorstand; kassenführung; kassenverwaltung',
        'schauspieler': 'rollen; besetzung; darstellende',
        'schirmherr': 'support; gefördert/unterstützt von...',
        'schirmherrschaft': 'support; gefördert/unterstützt von...',
        'schlichter': 'schlichtende; schlichtungsperson',
        'schneemann': 'schneefigur',
        'schöpfer': 'noch kein passender begriff gefunden;',
        'schöpfer': '(er-)schaffende',
        'schulabbrecher': 'geringqualifizierte; menschen ohne schulabschluss',
        'schuldiger': 'schuldige person',
        'schuldige': '[im plural ist dieses wort schon gendergerecht]',
        'schüler': 'schulkind',
        'schüler': 'schulkinder; kinder; jugendliche; die klasse; lernende; beschulte',
        'schüleraustausch': 'schulaustausch',
        'schülerbegegnung': 'schulbegegnung; klassenbegegnung',
        'seefahrer': 'seeleute',
        'seemann': 'hochsee-fachkraft; maritime fachkraft',
        'seinerzeit': 'zu jener zeit; damals; einst; früher',
        'seinesgleichen': 'von gleicher art',
        'sekretärin': 'verwaltungskraft; assistenz; schreibkraft; bürokraft',
        'sekretärinnen': 'verwaltungskräfte; verwaltungsfachangestellte; assistenzen; schreibkräfte; bürokräfte',
        'selbstmörder': 'einen selbstmord/suizid begehende person',
        'seminarleiter': 'seminarleitung',
        'sender': 'gesendet von...',
        'sender-nachricht-empfänger-modell (kommunikationsmodell)': 'noch kein passender begriff gefunden;',
        'sender': 'sendende',
        'senioren': 'ältere menschen; menschen im rentenalter',
        'sexist': 'sexistische person',
        'sieger': 'erster platz',
        'soldat': 'mitglied der streitkräfte eines landes',
        'sozialarbeiter': 'noch kein passender begriff gefunden;',
        'sozialarbeiter': 'sozialarbeitende',
        'sozialpädagoge': 'noch kein passender begriff gefunden;',
        'spaziergänger': 'wandersperson',
        'spaziergänger': 'noch kein passender begriff gefunden;',
        'spender': 'gebende; sponsoring; spenden',
        'spezialisten': 'sachkundige; fachleute; sachverständige',
        'spieler': 'teammitglied',
        'spieler': 'spielende; teammitglieder',
        'spion': 'auskundschaftende person; spionierende person',
        'sprecher': 'abgeordnete',
        'sprecher (radio, fernsehen, hörbuch)': 'stimme; text gesprochen von; moderation; kommentar; ansage',
        'sprecher': 'sprachrohr; pressestelle; öffentlichkeitsarbeit',
        'sponsoren': 'sponsoring; geldgebende personen/firmen',
        'sportfreunde': 'mitglieder des/unseres vereins',
        'sportler': 'noch kein passender begriff gefunden;',
        'sportler': 'sporttreibende',
        'staatsbürgerschaft': 'staatsangehörigkeit; nationalität',
        'staatsmänner': 'volksbeauftragte; menschen in der politik',
        'stadtführer': 'stadtführung; reiseleitung',
        'star': 'berühmte persönlichkeit; berühmtheit',
        'steinewerfer': 'steinewerfende; steine werfende personen',
        'stellvertreter': 'stellvertretung',
        'steuerhinterzieher': 'steuerhinterziehende',
        'stifterrat': 'stiftungsrat',
        'stifterversammlung': 'stiftungsversammlung',
        'stipendiaten': 'studierende mit stipendium',
        'strahlemann': 'sonnenschein',
        'student': 'mitglied der studierenden',
        'studenten': 'studierende',
        'studienanfänger': 'studienbeginnende; erstis; erstsemestrige',
        'studienbewerber': 'studienbewerbungen; einschreibungen',
        'tagesmutter': 'tagespflege(person); tagesbetreuung; tageseltern; kinderbetreuung',
        'tante-emma-laden': 'minimarkt; laden für waren des täglichen bedarfs',
        'täter': 'unrechtsperson',
        'täter': 'unrechtspersonen; tatbegehende; kriminelle; (straf-)tat begangen von...',
        'teamleiter': 'teamleitung',
        'techniker': 'technische fachkraft',
        'teilnehmer': 'teilnehmende; beteiligte; alle, die an ... teilnehmen; anwesende; anmeldungen',
        'teilnehmergebühr': 'teilnahmegebühr',
        'teilnehmerliste': 'teilnahmeliste; anwesenheitsliste; teilnehmendenliste',
        'teilnehmerzahl': 'teilnahmezahl; gruppengröße; anmeldezahl',
        'terrorist': 'des terrors verdächtigte person; eines terroranschlags überführte person',
        'terroristen': 'terrorisierende',
        'testleiter': 'testleitung',
        'theaterpädagoge': 'theaterpädagogische fachkraft',
        'theoretiker': 'theoretisch arbeitende',
        'therapeut': 'therapeutisches fachpersonal',
        'touristen': 'urlaubsgäste',
        'trainer': 'übungsleitung',
        'trainer': 'referierende; vortragende; unterrichtende; lehrende',
        'türke': 'türkischer gemüse-/obstladen; laden um die ecke; kleiner gemüseladen',
        'tutor': 'studentische hilfskraft',
        'tutoren': 'übungs(an)leitende; tutoriumsbegleitende; ratgebende; begleitung',
        'übermannen': 'überkommen; überwältigen',
        'übersetzer': 'übersetzende; literatur übersetzende',
        'übungsleiter': 'sportliche/technische/praktische anleitung; anleitende person',
        'umschüler': 'umlernende; umschulende; die zu qualifizierenden; personen in beruflicher neuorientierung',
        'unbemannt': 'maschinengesteuert; autonom; ferngesteuert; unbesetzt; robotisch',
        'unternehmer': 'noch kein passender begriff gefunden;',
        'unternehmer': 'selbstständige; wirtschaftstreibende; geschäftsleute',
        'unterstützer': 'support; geldgebende; förderung durch ...',
        'urheber': 'noch kein passender begriff gefunden;',
        'urheberrecht': 'copyright; recht auf geistiges eigentum',
        'urlauber': 'reisende',
        'user': 'nutzende; personen, die apps/software nutzen; mitglieder',
        'v-mann': 'v-person',
        'v-männer': 'v-leute',
        'vater': 'elternteil',
        'vaterland': 'heimatland; geburtsland; erstland',
        'väterlicherseits': '(vornamen-)licherseits [bei gleichgeschlechtlichen elternpaaren]',
        'veranstalter': 'veranstaltet durch/von',
        'verantwortlicher': 'die verantwortung tragende person; verantwortliche person',
        'verantwortliche': '[im plural ist dieses wort schon gendergerecht]',
        'verbandsgesellschafter': 'vertretungen / beteiligte der verbände',
        'verbandsvertreter': 'vertretungen / beteiligte der verbände',
        'verbraucher': 'kundschaft; konsumierende',
        'verbraucherschutz': 'noch kein passender begriff gefunden;',
        'verbraucherschützer': 'für den verbraucherschutz beauftragte person',
        'verbrecher': 'person, die eine straftat/ein verbrechen begeht',
        'verfasser': 'verfasst von; autorenschaft',
        'verkäufer': 'kaufhauspersonal; personal',
        'verkehrssünder': 'verkehrsregeln missachtende person',
        'verkehrsteilnehmer': 'verkehrsbeteiligte',
        'verleger': 'publizierende',
        'verlierer': 'der letzte platz',
        'verlierer': 'die letzten',
        'vermieter': 'vermietende person',
        'vermittler': 'mittelsperson',
        'versichertenkarte': 'versicherungskarte; gesundheitskarte',
        'versichertennummer': 'versicherungsnummer',
        'versicherungsnehmer': 'versicherte person',
        'versicherungsnehmer': 'versicherte personen; versicherte',
        'versuchsleiter': 'versuchsleitung',
        'verteidiger': 'verteidigung; rechtsvertretung',
        'vertragspartner': 'vertragsparteien',
        'vertreter': 'in vertretender position',
        'vertreter': 'vertreten durch; vertretung; delegierte; abgeordnete; beauftragte',
        'verwandter': 'familienmitglied',
        'veteran': 'noch kein passender begriff gefunden;',
        'vorgesetzter': 'führungskraft',
        'vormund': 'die vormundschaft innehabende person; vormundschaft',
        'vorläufer': 'älteres/altes modell',
        'vorreiter': 'person an der spitze; person, die etwas vorlebt; person, die voraus denkt/handelt',
        'vorsitzender': 'noch kein passender begriff gefunden;',
        'vorstand': 'vorstandsmitglied; im vorstand',
        'wächter': 'wache',
        'wähler': 'wahlberechtigte; alle, die zur wahl gegangen sind',
        'wählerinitiative': 'initiative der wahlberechtigten',
        'wählerverzeichnis': 'wahlverzeichnis',
        'wart': 'noch kein passender begriff gefunden;',
        'wegbereiter': 'weg bereitende person(en); prägende person(en)',
        'wegewart': 'noch kein passender begriff gefunden;',
        'weltmännisch': 'cosmopolitisch, weltgewandt',
        'weltmarktführer': 'weltmarktführende',
        'wettbewerber': 'konkurrenz; wettbewerbsteilnehmende',
        'wissenschaftler': 'forschende; wissenschaftliches personal der universität;',
        'witwer': 'verwitwete',
        'workshopleiter': 'workshopleitung',
        'zahnarztpraxis': 'praxis für zahnerhaltung; zahnmedizinische praxis; praxis für zahnmedizin',
        'zauberer': 'zaubertrick vorführende person',
        'zauberer': 'zauberkunstschaffende',
        'zehnkämpfer': 'am zehnkampf teilnehmende person',
        'zeitgenosse': 'mitmensch',
        'zeuge': 'bezeugende person',
        'zeugen': 'bezeugende',
        'zimmermädchen': 'servicekraft; raumpflege; reinigungskraft',
        'zuhörer': 'publikum; auditorium',
        'zuschauer': 'person aus dem publikum',
        'zuschauer': 'publikum',
        'zuständiger': 'zuständige person',
        'zuwanderer': 'zugewanderte; personen mit migrationshintergrund; eingewanderte; migrierte'
    };

    // Initialize the script
    self.init();
})();